### ISSUE TITLE
Exception in plugin Ceylon IDE

### ISSUE THREAD

**Issue by marudo** [ceylon/ceylon-ide-intellij#123]
I Installed the plugins Ceylon Runtime 1.2.3-v201603141919 and Ceylon IDE 1.2.3-v201603141919 in IntelliJ IDEA 2016.1.1 Ultimate Edition. I made my first Hello World program and tried to run it but always get the following error message:

>null
java.lang.AssertionError
	at org.intellij.plugins.ceylon.ide.runner.CeylonRunConfiguration$1.getBootstrapJarPath(CeylonRunConfiguration.java:99)
	at org.intellij.plugins.ceylon.ide.runner.CeylonRunConfiguration$1.createJavaParameters(CeylonRunConfiguration.java:78)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:34)
	at com.intellij.debugger.impl.GenericDebuggerRunner.createContentDescriptor(GenericDebuggerRunner.java:68)
	at com.intellij.debugger.impl.GenericDebuggerRunner.doExecute(GenericDebuggerRunner.java:62)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:389)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:161)
	at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:346)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by bjansen** [comment]
I think I fixed that problem this week, I'll have to take a look and confirm.

**Comment by maru75** [comment]
That was fast. I am looking forward to test it.

**Comment by bjansen** [comment]
Actually there's another problem now, I'm investigating.

**Comment by bjansen** [comment]
I uploaded a new build that fixes the problem, please hit "Check for updates" and keep me posted it something goes wrong again ;)

**Comment by bjansen** [comment]
The new version is 1.2.3-v201604082133

**Comment by MikhailMalyutin** [comment]
Looks like not fixed
java.lang.AssertionError
	at org.intellij.plugins.ceylon.ide.runner.CeylonRunConfiguration$1.getBootstrapJarPath(CeylonRunConfiguration.java:94)
In version Version: 1.2.3-201604200248

**Comment by hrjimgo** [comment]
Hello, I have problems with the Ceylon IDE plugin:
My code:
"Run the module `mymodule`."
shared void run() {
    print("hello");
}
Ceylon runtime version:1.2.3-v201604082133
Ceylon ide version:Version: 1.2.3-201604200248

Error message:
null
java.lang.AssertionError
	at org.intellij.plugins.ceylon.ide.runner.CeylonRunConfiguration$1.getBootstrapJarPath(CeylonRunConfiguration.java:94)
	at org.intellij.plugins.ceylon.ide.runner.CeylonRunConfiguration$1.createJavaParameters(CeylonRunConfiguration.java:78)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:34)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgramRunner.java:78)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:389)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:161)
	at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:346)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
