### ISSUE TITLE
ConcurrentModificationException in CeylonGotoClassContributor.getNames

### ISSUE THREAD

**Issue by azolotko** [ceylon/ceylon-ide-intellij#129]
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.intellij.plugins.ceylon.ide.codeInsight.navigation.CeylonGotoClassContributor.getNames(CeylonGotoClassContributor.java:63)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:116)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:97)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:112)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by azolotko** [comment]
```
IntelliJ IDEA 2016.1.1  Build #IC-145.597.3 
JDK: 1.8.0_40-release 
VM: OpenJDK 64-Bit Server VM 
Vendor: JetBrains s.r.o 
OS: Mac OS X
```

**Comment by azolotko** [comment]
ceylon-ide-intellij @ df30dab21a7e78df0e395213ca3d813d182be7d1

**Comment by azolotko** [comment]
jfyi: the issue is still relevant at 63f3cec
