### ISSUE TITLE
NCDFE after upgrading

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#139]
Just upgraded to the latest plugin in `http://downloads.ceylon-lang.org/ide/intellij/development/legacy/updatePlugins.xml` on Android Studio and got this at start up:

```
Start Failed: Internal Error. Please report to https://https://code.google.com/p/android/issues

java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.psi.stubs.StubUpdatingIndex'
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:201)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.psi.stubs.StubUpdatingIndex'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:245)
	at com.intellij.util.indexing.FileBasedIndexImpl.initExtensions(FileBasedIndexImpl.java:302)
	at com.intellij.util.indexing.FileBasedIndexImpl.initComponent(FileBasedIndexImpl.java:373)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:497)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:512)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:455)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:447)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: org/antlr/runtime/RecognitionException
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.stub.CeylonStubTypes.<clinit>(CeylonStubTypes.java:9)
	at org.intellij.plugins.ceylon.ide.parser.CeylonParserDefinition.getFileNodeType(CeylonParserDefinition.java:37)
	at com.intellij.psi.stubs.CumulativeStubVersion.getCumulativeVersion(CumulativeStubVersion.java:38)
	at com.intellij.psi.stubs.StubUpdatingIndex.getVersion(StubUpdatingIndex.java:228)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:393)
	at com.intellij.util.indexing.FileBasedIndexImpl.initExtensions(FileBasedIndexImpl.java:296)
	... 31 more
Caused by: java.lang.ClassNotFoundException: org.antlr.runtime.RecognitionException PluginClassLoader[org.intellij.plugins.ceylon.ide, 1.2.3-201604201119]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more

```

**Comment by FroMage** [comment]
This actually blocks AS from opening at all :( It doesn't "just" disable the plugin.

**Comment by FroMage** [comment]
Works on non-legacy current repo.
