### ISSUE TITLE
Other NPE

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#142]
```
null
java.lang.NullPointerException
	at com.redhat.ceylon.compiler.java.loader.model.LazyModuleSourceMapper.attachErrorToDependencyDeclaration(LazyModuleSourceMapper.java:191)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleHelper.buildErrorOnMissingArtifact(ModuleHelper.java:54)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.resolveModuleIfRequired(ModuleValidator.java:267)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.access$300(ModuleValidator.java:39)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:107)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:48)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:73)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:97)
	at com.redhat.ceylon.ide.common.model.CeylonProject$12$1.$call$(CeylonProject.ceylon:890)
	at com.redhat.ceylon.ide.common.model.withCeylonModelCaching_.withCeylonModelCaching(CeylonProjects.ceylon:40)
	at com.redhat.ceylon.ide.common.model.CeylonProject$12.$call$(CeylonProject.ceylon:740)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:420)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:412)
	at com.redhat.ceylon.ide.common.model.CeylonProject.parseCeylonModel(CeylonProject.ceylon:737)
	at org.intellij.plugins.ceylon.ide.annotator.TypeCheckerProvider$1.run(TypeCheckerProvider.java:130)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by bjansen** [comment]
Are you using a JDK provider other than `android/23`?

**Comment by FroMage** [comment]
Nope.

**Comment by bjansen** [comment]
This has been fixed: if the custom JDK provider is not found in the local repository, an error is shown in the UI.
