### ISSUE TITLE
NPE in Rename

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#166]
Just got this:

```
null
java.lang.NullPointerException
	at org.intellij.plugins.ceylon.ide.codeInsight.resolve.CeylonFindUsagesProvider.getDescriptiveName(CeylonFindUsagesProvider.java:90)
	at com.intellij.lang.findUsages.DescriptiveNameUtil.getDescriptiveName(DescriptiveNameUtil.java:53)
	at com.intellij.refactoring.rename.RenameDialog.getFullName(RenameDialog.java:141)
	at com.intellij.refactoring.rename.RenameDialog.getLabelText(RenameDialog.java:113)
	at com.intellij.refactoring.rename.RenameDialog.<init>(RenameDialog.java:86)
	at org.intellij.plugins.ceylon.ide.refactoring.CeylonRenamePsiProcessor$1.<init>(CeylonRenamePsiProcessor.java:22)
	at org.intellij.plugins.ceylon.ide.refactoring.CeylonRenamePsiProcessor.createRenameDialog(CeylonRenamePsiProcessor.java:22)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:177)
```

**Comment by gavinking** [comment]
And this:

```
java.lang.UnsupportedOperationException: Descriptive name not implemented for class org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonPsiImpl$IdentifierPsiImpl
	at org.intellij.plugins.ceylon.ide.codeInsight.resolve.CeylonFindUsagesProvider.getDescriptiveName(CeylonFindUsagesProvider.java:110)
	at com.intellij.lang.findUsages.DescriptiveNameUtil.getDescriptiveName(DescriptiveNameUtil.java:53)
	at com.intellij.refactoring.rename.RenameDialog.getFullName(RenameDialog.java:141)
	at com.intellij.refactoring.rename.RenameDialog.getLabelText(RenameDialog.java:113)
	at com.intellij.refactoring.rename.RenameDialog.<init>(RenameDialog.java:86)
	at org.intellij.plugins.ceylon.ide.refactoring.CeylonRenamePsiProcessor$1.<init>(CeylonRenamePsiProcessor.java:22)
	at org.intellij.plugins.ceylon.ide.refactoring.CeylonRenamePsiProcessor.createRenameDialog(CeylonRenamePsiProcessor.java:22)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:177)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:169)
````

**Comment by gavinking** [comment]
@bjansen This bug still occurs for:

1. control structure variables (e.g. `if (exists name = ... )`), and
2. anonymous function parameters.

```
Descriptive name not implemented for class org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonPsiImpl$VariablePsiImpl
java.lang.UnsupportedOperationException: Descriptive name not implemented for class org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonPsiImpl$VariablePsiImpl
	at org.intellij.plugins.ceylon.ide.codeInsight.resolve.CeylonFindUsagesProvider.getDescriptiveName(CeylonFindUsagesProvider.java:110)
	at com.intellij.lang.findUsages.DescriptiveNameUtil.getDescriptiveName(DescriptiveNameUtil.java:53)
	at com.intellij.refactoring.rename.RenameDialog.getFullName(RenameDialog.java:141)
	at com.intellij.refactoring.rename.RenameDialog.getLabelText(RenameDialog.java:113)
	at com.intellij.refactoring.rename.RenameDialog.<init>(RenameDialog.java:86)
	at org.intellij.plugins.ceylon.ide.refactoring.CeylonRenamePsiProcessor$1.<init>(CeylonRenamePsiProcessor.java:22)
	at org.intellij.plugins.ceylon.ide.refactoring.CeylonRenamePsiProcessor.createRenameDialog(CeylonRenamePsiProcessor.java:22)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:177)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:169)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:119)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:79)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.performDialogRename(VariableInplaceRenameHandler.java:138)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.doRename(VariableInplaceRenameHandler.java:124)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.invoke(VariableInplaceRenameHandler.java:90)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:134)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bjansen** [comment]
Dude, I just pushed a fix, you didn't even have time to rebuild the plugin and test it.

**Comment by gavinking** [comment]
Oh, haha, what happened was I ran into the bug again, and was searching for the existing issue and found it closed. Did not notice you had only *just* closed it :-)
