### ISSUE TITLE
truncated documentation for native stuff in language module

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#170]
The documentation for stuff like `String`, `Integer`, `Array`, `Character`, etc in the language module is truncated or missing. It *is* available for non-native declarations.

**Comment by bjansen** [comment]
It's truncated because the doc is truncated in `String.class`:

```
@com.redhat.ceylon.compiler.java.metadata.Annotation(value="doc", arguments={"A string of characters..."})
```

**Comment by gavinking** [comment]
Right. You're not supposed to be getting it from there. You're supposed to be getting it from the source archive. Ask @davidfestal how.

**Comment by gavinking** [comment]
@bjansen Still doesn't work for `String`, due to:

```
null
java.lang.AssertionError
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.consumeTokens(IdeaCeylonParser.java:313)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:247)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visit(IdeaCeylonParser.java:164)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser.doParseContents(IdeaCeylonParser.java:99)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:511)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:497)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:612)
	at com.intellij.psi.util.PsiTreeUtil.findElementOfClassAtOffset(PsiTreeUtil.java:779)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation.gotoLocation(ideaNavigation.ceylon:125)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation.gotoLocation(ideaNavigation.ceylon:60)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoNode(AbstractNavigation.ceylon:77)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoDeclaration(AbstractNavigation.ceylon:36)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolveDeclaration(CeylonReference.java:78)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.java:65)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:403)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:380)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:247)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:216)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorPsiDataProvider.getPsiElementIn(TextEditorPsiDataProvider.java:193)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorPsiDataProvider.getData(TextEditorPsiDataProvider.java:80)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.getData(FileEditorManagerEx.java:176)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.getData(TextEditorComponent.java:270)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.getData(PsiAwareTextEditorImpl.java:87)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:81)
	at com.intellij.ide.impl.DataManagerImpl.getData(DataManagerImpl.java:69)
	at com.intellij.ide.impl.DataManagerImpl.access$300(DataManagerImpl.java:55)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.doGetData(DataManagerImpl.java:398)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:375)
	at com.intellij.openapi.actionSystem.DataContextWrapper.getData(DataContextWrapper.java:38)
	at com.intellij.openapi.actionSystem.AnActionEvent$1.getData(AnActionEvent.java:145)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:75)
	at com.intellij.codeInsight.documentation.actions.ShowQuickDocInfoAction.update(ShowQuickDocInfoAction.java:78)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:246)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:117)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:622)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



java.lang.AssertionError
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.consumeTokens(IdeaCeylonParser.java:313)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:247)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visit(IdeaCeylonParser.java:164)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser.doParseContents(IdeaCeylonParser.java:99)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:511)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:497)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:612)
	at com.intellij.psi.util.PsiTreeUtil.findElementOfClassAtOffset(PsiTreeUtil.java:779)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation.gotoLocation(ideaNavigation.ceylon:125)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation.gotoLocation(ideaNavigation.ceylon:60)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoNode(AbstractNavigation.ceylon:77)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoDeclaration(AbstractNavigation.ceylon:36)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolveDeclaration(CeylonReference.java:78)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.java:65)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:403)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:380)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:247)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:216)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



java.lang.AssertionError
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.consumeTokens(IdeaCeylonParser.java:313)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:247)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visit(IdeaCeylonParser.java:164)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser.doParseContents(IdeaCeylonParser.java:99)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:511)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:497)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:612)
	at com.intellij.psi.util.PsiTreeUtil.findElementOfClassAtOffset(PsiTreeUtil.java:779)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation.gotoLocation(ideaNavigation.ceylon:125)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation.gotoLocation(ideaNavigation.ceylon:60)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoNode(AbstractNavigation.ceylon:77)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoDeclaration(AbstractNavigation.ceylon:36)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolveDeclaration(CeylonReference.java:78)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.java:65)
	at com.intellij.codeInsight.intention.AddAnnotationPsiFix.getContainer(AddAnnotationPsiFix.java:73)
	at com.intellij.codeInsight.intention.impl.AddAnnotationIntention.isAvailable(AddAnnotationIntention.java:51)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:128)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:307)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:304)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:153)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:304)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:201)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



java.lang.AssertionError
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.consumeTokens(IdeaCeylonParser.java:313)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:247)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:244)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visit(IdeaCeylonParser.java:164)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser.doParseContents(IdeaCeylonParser.java:99)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:511)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:497)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:612)
	at com.intellij.psi.util.PsiTreeUtil.findElementOfClassAtOffset(PsiTreeUtil.java:779)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation.gotoLocation(ideaNavigation.ceylon:125)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation.gotoLocation(ideaNavigation.ceylon:60)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoNode(AbstractNavigation.ceylon:77)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoDeclaration(AbstractNavigation.ceylon:36)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolveDeclaration(CeylonReference.java:78)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.java:65)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:403)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:380)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:247)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:216)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by bjansen** [comment]
See my comment in #180
