### ISSUE TITLE
Extract Variable crashes

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#172]
Sometimes, but not always, this happens:

```
null value returned from native call not assignable to Object
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.refactoring.ExtractValueRefactoring$impl.build(ExtractValueRefactoring.ceylon:75)
	at org.intellij.plugins.ceylon.ide.ceylonCode.refactoring.IdeaExtractValueRefactoring.build(IdeaExtractValueRefactoring.ceylon)
	at org.intellij.plugins.ceylon.ide.ceylonCode.refactoring.IdeaExtractValueRefactoring.extractInFile(IdeaExtractValueRefactoring.ceylon:119)
	at org.intellij.plugins.ceylon.ide.ceylonCode.refactoring.ExtractValueHandler.extract(IdeaExtractValueRefactoring.ceylon:81)
	at org.intellij.plugins.ceylon.ide.ceylonCode.refactoring.AbstractExtractHandler.createAndIntroduceValue$priv$(AbstractExtractHandler.ceylon:111)
	at org.intellij.plugins.ceylon.ide.ceylonCode.refactoring.AbstractExtractHandler.invoke(AbstractExtractHandler.ceylon:72)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:134)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
```

**Comment by gavinking** [comment]
Also affects Extract Method.
