### ISSUE TITLE
Can't navigate to ArrayList.initialCapacity

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#178]
Given:

```ceylon
value list = ArrayList { initialCapacity = 1; "hello", "world" };
```

If I try to navigate to `initialCapacity` by clicking, I get:

```
null value returned from native call not assignable to Object
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visit(FindReferencedNodeVisitor.ceylon:74)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AttributeSetterDefinition.visit(Tree.java:1328)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:435)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassBody(Walker.java:444)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visitChildren(Tree.java:1870)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visitAny(FindReferencedNodeVisitor.ceylon:123)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:69)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:71)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visit(Tree.java:1862)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassDefinition(Walker.java:248)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visitChildren(Tree.java:949)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visitAny(FindReferencedNodeVisitor.ceylon:123)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:118)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visit(FindReferencedNodeVisitor.ceylon:56)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:28)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:29)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:41)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:941)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visitAny(FindReferencedNodeVisitor.ceylon:123)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.ide.common.util.nodes_.getReferencedNodeInUnit(nodes.ceylon:527)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoDeclaration(AbstractNavigation.ceylon:32)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolveDeclaration(CeylonReference.java:78)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.java:65)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:403)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:380)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:247)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:216)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visit(FindReferencedNodeVisitor.ceylon:74)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AttributeSetterDefinition.visit(Tree.java:1328)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:435)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassBody(Walker.java:444)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visitChildren(Tree.java:1870)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visitAny(FindReferencedNodeVisitor.ceylon:123)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:69)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:71)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visit(Tree.java:1862)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassDefinition(Walker.java:248)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visitChildren(Tree.java:949)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visitAny(FindReferencedNodeVisitor.ceylon:123)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:118)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visit(FindReferencedNodeVisitor.ceylon:56)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:28)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:29)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:41)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:941)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visitAny(FindReferencedNodeVisitor.ceylon:123)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.ide.common.util.nodes_.getReferencedNodeInUnit(nodes.ceylon:527)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoDeclaration(AbstractNavigation.ceylon:32)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolveDeclaration(CeylonReference.java:78)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.java:65)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:403)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:380)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:247)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:216)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visit(FindReferencedNodeVisitor.ceylon:74)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AttributeSetterDefinition.visit(Tree.java:1328)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:435)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassBody(Walker.java:444)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visitChildren(Tree.java:1870)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visitAny(FindReferencedNodeVisitor.ceylon:123)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:69)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:71)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visit(Tree.java:1862)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassDefinition(Walker.java:248)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visitChildren(Tree.java:949)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visitAny(FindReferencedNodeVisitor.ceylon:123)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:118)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visit(FindReferencedNodeVisitor.ceylon:56)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:28)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:29)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:41)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:941)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.ide.common.util.FindReferencedNodeVisitor.visitAny(FindReferencedNodeVisitor.ceylon:123)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.ide.common.util.nodes_.getReferencedNodeInUnit(nodes.ceylon:527)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoDeclaration(AbstractNavigation.ceylon:32)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolveDeclaration(CeylonReference.java:78)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.java:65)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:403)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:380)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:247)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:216)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by gavinking** [comment]
Confirmed.
