### ISSUE TITLE
linked mode argument completions don't usually appear

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#179]
Completing, for example, `print()`, or `printAll()` results in:

```
null value returned from native call not assignable to Object
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaInvocationCompletionProposal.newNestedCompletionProposal(IdeaInvocationCompletionProposal.ceylon:82)
	at com.redhat.ceylon.ide.common.completion.InvocationCompletionProposal.addValueArgumentProposal$priv$(InvocationCompletion.ceylon:886)
	at com.redhat.ceylon.ide.common.completion.InvocationCompletionProposal.addValueArgumentProposals$priv$(InvocationCompletion.ceylon:796)
	at com.redhat.ceylon.ide.common.completion.InvocationCompletionProposal.enterLinkedMode(InvocationCompletion.ceylon:717)
	at com.redhat.ceylon.ide.common.completion.InvocationCompletionProposal.activeLinkedMode(InvocationCompletion.ceylon:597)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaInvocationCompletionProposal$1anonymous_0_.handleInsert(IdeaInvocationCompletionProposal.ceylon:71)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.newLookup_$1anonymous_0_.handleInsert(IdeaCompletionProposal.ceylon:75)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.handleInsert(LookupElementBuilder.java:384)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$10.run(CodeCompletionHandlerBase.java:708)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.insertItem(CodeCompletionHandlerBase.java:696)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.access$500(CodeCompletionHandlerBase.java:70)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$7.perform(CodeCompletionHandlerBase.java:626)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:345)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:425)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:336)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:327)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.insertItemHonorBlockSelection(CodeCompletionHandlerBase.java:614)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lookupItemSelected(CodeCompletionHandlerBase.java:583)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$2.itemSelected(CompletionProgressIndicator.java:117)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.fireItemSelected(LookupImpl.java:827)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:529)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:468)
	at com.intellij.codeInsight.lookup.impl.actions.ChooseItemAction$Handler.execute(ChooseItemAction.java:71)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doExecute(EditorActionHandler.java:172)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by gavinking** [comment]
Perfect, much better :)
