### ISSUE TITLE
CME after rebuild

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#211]
```
null
java.util.ConcurrentModificationException
	at gnu.trove.THashIterator.nextIndex(THashIterator.java:83)
	at gnu.trove.TIterator.moveToNextIndex(TIterator.java:88)
	at gnu.trove.THashIterator.next(THashIterator.java:67)
	at gnu.trove.THashMap$MapBackedView.toArray(THashMap.java:663)
	at org.intellij.plugins.ceylon.ide.codeInsight.navigation.CeylonGotoClassContributor.getNames(CeylonGotoClassContributor.java:90)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:116)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:97)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:217)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:146)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
```

**Comment by bjansen** [comment]
I got this too, but it should be fixed in 9056c6756c69812287abd941de666187c31a3078.
