### ISSUE TITLE
⌥⌘B assertion failure for language module declarations

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#220]
When I look for implementations of something belonging to the language module, I get:

```
null value returned from native call not assignable to Object
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonImplementationsSearch.execute(CeylonImplementationsSearch.ceylon:64)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonImplementationsSearch.execute(CeylonImplementationsSearch.ceylon:52)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.codeInsight.navigation.ImplementationSearcher$FirstImplementationsSearcher$1.run(ImplementationSearcher.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonImplementationsSearch.execute(CeylonImplementationsSearch.ceylon:64)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonImplementationsSearch.execute(CeylonImplementationsSearch.ceylon:52)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.codeInsight.navigation.ImplementationSearcher$FirstImplementationsSearcher$1.run(ImplementationSearcher.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gavinking** [comment]
Well, OK, you squashed the assertion failure, but the thing still doesn't actually *work*!
