### ISSUE TITLE
⌥⌘B for type in binary module

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#225]
If I invoke Navigate > Implementations on a type from a binary module, for example, `Object`, or `MutableList`, no results are shown.

**Comment by bjansen** [comment]
I suppose you're only talking about declarations in .src files, not declarations decompiled from .car files?

**Comment by gavinking** [comment]
yes.

**Comment by gavinking** [comment]
Great! Thank you!

**Comment by gavinking** [comment]
This issue has returned. Might be related to this error:

```
null
java.lang.AssertionError
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.consumeTokens(IdeaCeylonParser.java:317)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:251)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:248)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:248)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:248)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visitAny(IdeaCeylonParser.java:248)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$AstVisitor.visit(IdeaCeylonParser.java:164)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser.doParseContents(IdeaCeylonParser.java:99)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:511)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:497)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:612)
	at com.intellij.psi.util.PsiUtilCore.getElementAtOffset(PsiUtilCore.java:420)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonTreeUtil.findPsiElement(CeylonTreeUtil.java:40)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonImplementationsSearch$1anonymous_0_.run(CeylonImplementationsSearch.ceylon:109)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonImplementationsSearch.scanPhasedUnits$priv$(CeylonImplementationsSearch.ceylon:112)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonImplementationsSearch.execute(CeylonImplementationsSearch.ceylon:76)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonImplementationsSearch.execute(CeylonImplementationsSearch.ceylon:56)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.codeInsight.navigation.ImplementationSearcher$FirstImplementationsSearcher$1.run(ImplementationSearcher.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bjansen** [comment]
Try a `File > Synchronize` maybe?

**Comment by gavinking** [comment]
Didn't help.

**Comment by bjansen** [comment]
or `File > Invalidate caches`

Somehow, IntelliJ fails to detect changes in `.src` files, so it tries to parse the old version of source files. OTOH, compilation units are built using the up-to-date source files, because source files are read by `net.lingala.zip4j-1.3.2.jar`, so when our parser compares the old text with the compilation unit, it fails with the error you pasted above.

**Comment by gavinking** [comment]
can't we catch that error and force a refresh of the file?

**Comment by gavinking** [comment]
OK, so yes, that was it. But isn't there something we can do to stop this happening again?

**Comment by bjansen** [comment]
It might be the same problem as this one: https://youtrack.jetbrains.com/issue/IDEA-156337

I suppose I can parse from the compilation unit's text, not from what IntelliJ gives me.

**Comment by gavinking** [comment]
Now #287.
