### ISSUE TITLE
CCE to do with Exception subtypes

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#244]
When I try to do stuff with `Exception` and its subtypes, for example, play with the Structure of `AssertionError`, I get errors like this:

```
com.intellij.psi.impl.source.PsiJavaFileImpl cannot be cast to org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonFile
java.lang.ClassCastException: com.intellij.psi.impl.source.PsiJavaFileImpl cannot be cast to org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonFile
	at org.intellij.plugins.ceylon.ide.structureView.CeylonInheritedMembersNodeProvider.provideNodes(CeylonInheritedMembersNodeProvider.java:72)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:60)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:203)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:51)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:44)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$StructureViewTreeElementWrapper.getChildren(StructureViewComponent.java:841)
	at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:55)
	at com.intellij.ide.util.treeView.AbstractTreeUi$32.perform(AbstractTreeUi.java:1620)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
	at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1617)
	at com.intellij.ide.util.treeView.AbstractTreeUi.loadElementsFromStructure(AbstractTreeUi.java:2208)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildrenNow(AbstractTreeUi.java:1361)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1283)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$3200(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$26$1.perform(AbstractTreeUi.java:1175)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$26.perform(AbstractTreeUi.java:1172)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1167)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2100(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$51$3.perform(AbstractTreeUi.java:3126)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.TreeRunnable$TreeConsumer.consume(TreeRunnable.java:45)
	at org.jetbrains.concurrency.DonePromise.done(DonePromise.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi$51.consume(AbstractTreeUi.java:3086)
	at com.intellij.ide.util.treeView.AbstractTreeUi$51.consume(AbstractTreeUi.java:3025)
	at org.jetbrains.concurrency.DonePromise.done(DonePromise.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNode(AbstractTreeUi.java:3025)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5100(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$33$1.run(AbstractTreeUi.java:1722)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1817)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5400(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$34.perform(AbstractTreeUi.java:1783)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2092)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$6000(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$37$1.perform(AbstractTreeUi.java:1984)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2187)
	at com.intellij.ide.util.treeView.AbstractTreeUi$37.perform(AbstractTreeUi.java:1979)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by gavinking** [comment]
Or this slightly-different one:

```
com.intellij.psi.impl.source.PsiJavaFileImpl cannot be cast to org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonFile
java.lang.ClassCastException: com.intellij.psi.impl.source.PsiJavaFileImpl cannot be cast to org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonFile
	at org.intellij.plugins.ceylon.ide.structureView.CeylonInheritedMembersNodeProvider.provideNodes(CeylonInheritedMembersNodeProvider.java:72)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.initChildren(TreeElementWrapper.java:60)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.rebuildSubtree(CachingChildrenTreeNode.java:203)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.ensureChildrenAreInitialized(CachingChildrenTreeNode.java:51)
	at com.intellij.ide.util.treeView.smartTree.CachingChildrenTreeNode.getChildren(CachingChildrenTreeNode.java:44)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$StructureViewTreeElementWrapper.getChildren(StructureViewComponent.java:841)
	at com.intellij.ide.util.treeView.smartTree.SmartTreeStructure.getChildElements(SmartTreeStructure.java:55)
	at com.intellij.ide.util.treeView.AbstractTreeUi$32.perform(AbstractTreeUi.java:1620)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
	at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1617)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$4800(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$31.perform(AbstractTreeUi.java:1542)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processUnbuilt(AbstractTreeUi.java:1529)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1252)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$3200(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$26$1.perform(AbstractTreeUi.java:1175)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$26.perform(AbstractTreeUi.java:1172)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1167)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodesToInsert(AbstractTreeUi.java:1672)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$4400(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$30$2.consume(AbstractTreeUi.java:1399)
	at com.intellij.ide.util.treeView.AbstractTreeUi$30$2.consume(AbstractTreeUi.java:1395)
	at com.intellij.openapi.util.AsyncResult$2.run(AsyncResult.java:100)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.openapi.util.AsyncResult.doWhenDone(AsyncResult.java:97)
	at com.intellij.ide.util.treeView.AbstractTreeUi$30.perform(AbstractTreeUi.java:1395)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.TreeRunnable$TreeConsumer.consume(TreeRunnable.java:45)
	at org.jetbrains.concurrency.AsyncPromise.setResult(AsyncPromise.java:314)
	at org.jetbrains.concurrency.DonePromise.notify(DonePromise.java:88)
	at com.intellij.ide.util.treeView.AbstractTreeUi$34.perform(AbstractTreeUi.java:1783)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2092)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$6000(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$37$1.perform(AbstractTreeUi.java:1984)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2187)
	at com.intellij.ide.util.treeView.AbstractTreeUi$37.perform(AbstractTreeUi.java:1979)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by gavinking** [comment]
Appears to be fixed now.

**Comment by bjansen** [comment]
The error is still here, for example when you show the structure (including inherited members) of this declaration:

```ceylon
class Foo() extends Exception() {
}
```

**Comment by gavinking** [comment]
ok, sorry.

**Comment by gavinking** [comment]
Ah, right, it is specifically with inherited members displayed that the error happens. OK.

**Comment by gavinking** [comment]
Thanks, looks good.
