### ISSUE TITLE
NPE during completion

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#282]
```
null
java.lang.NullPointerException
	at com.redhat.ceylon.model.loader.AbstractModelLoader.obtainTypeParameterBound(AbstractModelLoader.java:5273)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.applyTypeArguments(AbstractModelLoader.java:5235)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.obtainTypeParameterBound(AbstractModelLoader.java:5293)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.applyTypeArguments(AbstractModelLoader.java:5207)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.obtainTypeParameterBound(AbstractModelLoader.java:5293)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.applyTypeArguments(AbstractModelLoader.java:5207)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getNonPrimitiveType(AbstractModelLoader.java:5132)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.obtainType(AbstractModelLoader.java:5032)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.obtainType(AbstractModelLoader.java:4987)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.addMethod(AbstractModelLoader.java:3414)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2849)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2266)
	at com.redhat.ceylon.model.loader.model.LazyClass.load(LazyClass.java:101)
	at com.redhat.ceylon.model.loader.model.LazyClass.getParameterLists(LazyClass.java:176)
	at com.redhat.ceylon.ide.common.completion.InvocationCompletion$impl.addInvocationProposals(InvocationCompletion.ceylon:308)
	at com.redhat.ceylon.ide.common.completion.completionManager_.addInvocationProposals(IdeCompletionManager.ceylon)
	at com.redhat.ceylon.ide.common.completion.completionManager_.constructCompletions$priv$(IdeCompletionManager.ceylon:832)
	at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals$canonical$(IdeCompletionManager.ceylon:268)
	at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals(IdeCompletionManager.ceylon:107)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.addCompletionsInternal$priv$(ideaCompletionManager.ceylon:140)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.access$000(ideaCompletionManager.ceylon:61)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider$1.$call$(ideaCompletionManager.ceylon:117)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:180)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:192)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.addCompletions(ideaCompletionManager.ceylon:113)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:817)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$1000(CompletionProgressIndicator.java:88)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:799)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:89)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bjansen** [comment]
I think it's been fixed in dd1ed3f91cead0a98801c12a77df4aa3c386f26b.
