### ISSUE TITLE
error occurring creating a new project

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#308]
I got a couple of these when I tried to create a new project:

```
java.io.FileNotFoundException: Invalid path: $MODULE_DIR$/modules
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl$WatchRequestImpl.<init>(LocalFileSystemImpl.java:74)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl.watch(LocalFileSystemImpl.java:489)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl.doAddRootsToWatch(LocalFileSystemImpl.java:433)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl.access$1000(LocalFileSystemImpl.java:54)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl$5.run(LocalFileSystemImpl.java:409)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:945)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl.replaceWatchedRoots(LocalFileSystemImpl.java:405)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.addRootsToWatch(ProjectRootManagerComponent.java:150)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:421)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:55)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.fireChange(ProjectRootManagerImpl.java:112)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:125)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:357)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModel(ModuleManagerImpl.java:948)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.access$1800(ModuleManagerImpl.java:71)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.commitWithRunnable(ModuleManagerImpl.java:854)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.access$1600(ModuleManagerImpl.java:616)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModelWithRunnable(ModuleManagerImpl.java:607)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:48)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:37)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.commit(ModuleManagerImpl.java:850)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.createAndCommitIfNeeded(ModuleBuilder.java:302)
	at com.intellij.ide.util.projectWizard.ModuleBuilder$4.compute(ModuleBuilder.java:355)
	at com.intellij.ide.util.projectWizard.ModuleBuilder$4.compute(ModuleBuilder.java:352)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1033)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commitModule(ModuleBuilder.java:352)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commit(ModuleBuilder.java:338)
	at com.intellij.ide.util.projectWizard.JavaModuleBuilder.commit(JavaModuleBuilder.java:167)
	at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.java:164)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:79)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.java:74)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:31)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:64)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:116)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:77)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:287)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by gavinking** [comment]
I also get these at startup time:

```
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:138)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1054)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:182)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:799)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:1004)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:43)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:30)
	at com.intellij.util.WalkingState.next(WalkingState.java:73)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:61)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:73)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:718)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:713)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfAnyType(PsiTreeUtil.java:256)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:206)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonFile.getCompilationUnitPsi(CeylonFile.java:27)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonFile.getCompilationUnit(CeylonFile.java:31)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$1$1syntaxErrorsWhenOnlyOneCeylonChange_.syntaxErrorsWhenOnlyOneCeylonChange(CeylonModelManager.ceylon:242)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$1.$call$(CeylonModelManager.ceylon:256)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

**Comment by gavinking** [comment]
👍
