### ISSUE TITLE
IDE locked during startup

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#309]
Not sure what happened, I think IDEA detected a corruption in its cache and decided to update it while we were building the Ceylon model.

```
2016-06-16 10:24:12,600 [  14101]   INFO - il.indexing.FileBasedIndexImpl - Rebuild requested for index Stubs 
java.lang.Throwable: java.io.IOException: org.iq80.snappy.CorruptionException: Corrupt literal length
	at com.intellij.util.indexing.FileBasedIndexImpl.scheduleRebuild(FileBasedIndexImpl.java:1132)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:846)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesImpl(FileBasedIndexImpl.java:904)
	at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java:770)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:92)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:49)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStubTree(ClsFileImpl.java:485)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:72)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:324)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:675)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:663)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:350)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:316)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:146)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:91)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:126)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:122)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:99)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$3$1.$call$(IdeaModelLoader.ceylon:132)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$3$1.$call$(IdeaModelLoader.ceylon:127)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$2.$call$(concurrencyManager.ceylon:151)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1033)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$1runInReadActionWithWriteActionPriority_$2.$call$(concurrencyManager.ceylon:132)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$1runInReadActionWithWriteActionPriority_.runInReadActionWithWriteActionPriority(concurrencyManager.ceylon:129)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needReadAccess$canonical$(concurrencyManager.ceylon:150)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needReadAccess(concurrencyManager.ceylon:94)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.doWithLock_.doWithLock(concurrencyManager.ceylon:267)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$3.$call$(IdeaModelLoader.ceylon:127)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$3.$call$(IdeaModelLoader.ceylon:127)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$3.$call$(concurrencyManager.ceylon:226)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.project.DumbService.repeatUntilPassesInSmartMode(DumbService.java:145)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needIndexes(concurrencyManager.ceylon:241)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.buildClassMirrorInternal(IdeaModelLoader.ceylon:127)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$11.$call$(IdeModelLoader.ceylon:525)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$11.$call$(IdeModelLoader.ceylon:516)
	at com.redhat.ceylon.ide.common.util.synchronize_.synchronize(synchronize_.java:33)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.lookupNewClassMirror(IdeModelLoader.ceylon:555)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.lookupClassMirror(AbstractModelLoader.java:390)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadClass(AbstractModelLoader.java:554)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadCompiledModule(AbstractModelLoader.java:2057)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadCompiledModule(AbstractModelLoader.java:2045)
	at com.redhat.ceylon.compiler.java.loader.model.LazyModuleSourceMapper.resolveModule(LazyModuleSourceMapper.java:128)
	at com.redhat.ceylon.ide.common.model.BaseIdeModuleSourceMapper.resolveModule(IdeModuleSourceMapper.ceylon:142)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.resolveModuleIfRequired(ModuleValidator.java:294)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:227)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.access$500(ModuleValidator.java:40)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:119)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:50)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:75)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:98)
	at com.redhat.ceylon.ide.common.model.CeylonProject$13$1.$call$(CeylonProject.ceylon:910)
	at com.redhat.ceylon.ide.common.model.withCeylonModelCaching_.withCeylonModelCaching(CeylonProjects.ceylon:47)
	at com.redhat.ceylon.ide.common.model.CeylonProject$13.$call$(CeylonProject.ceylon:745)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:432)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:424)
	at com.redhat.ceylon.ide.common.model.CeylonProject.parseCeylonModel(CeylonProject.ceylon:742)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.resolveClasspath$priv$(CeylonProjectBuild.ceylon:553)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild$canonical$(CeylonProjectBuild.ceylon:568)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild(CeylonProjectBuild.ceylon:559)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$1$2$1anonymous_2_$1.$call$(CeylonModelManager.ceylon:288)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:188)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:209)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$1$2$1anonymous_2_.run(CeylonModelManager.ceylon:284)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: org.iq80.snappy.CorruptionException: Corrupt literal length
	at com.intellij.util.io.CompressedAppendableFile.loadChunk(CompressedAppendableFile.java:207)
	at com.intellij.util.io.CompressedAppendableFile.access$700(CompressedAppendableFile.java:36)
	at com.intellij.util.io.CompressedAppendableFile$FileChunkReadCache.get(CompressedAppendableFile.java:482)
	at com.intellij.util.io.CompressedAppendableFile$SegmentedChunkInputStream.read(CompressedAppendableFile.java:522)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at com.intellij.util.io.PersistentHashMapValueStorage.readBytes(PersistentHashMapValueStorage.java:377)
	at com.intellij.util.io.PersistentHashMap.doGet(PersistentHashMap.java:518)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:472)
	at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:122)
	at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:110)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.getMergedData(ChangeTrackingValueContainer.java:121)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:82)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processValuesImpl$2(FileBasedIndexImpl.java:869)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:833)
	... 87 more
Caused by: org.iq80.snappy.CorruptionException: Corrupt literal length
	at org.iq80.snappy.SnappyDecompressor.copyLiteral(SnappyDecompressor.java:285)
	at org.iq80.snappy.SnappyDecompressor.decompressAllTags(SnappyDecompressor.java:118)
	at org.iq80.snappy.SnappyDecompressor.uncompress(SnappyDecompressor.java:47)
	at org.iq80.snappy.Snappy.uncompress(Snappy.java:37)
	at com.intellij.util.CompressionUtil.readCompressedWithoutOriginalBufferLength(CompressionUtil.java:97)
	at com.intellij.util.io.CompressedAppendableFile.decompress(CompressedAppendableFile.java:370)
	at com.intellij.util.io.CompressedAppendableFile.loadChunk(CompressedAppendableFile.java:191)
	... 100 more
2016-06-16 10:24:12,809 [  14310]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2016-06-16 10:24:12,809 [  14310]   INFO - penapi.project.DumbServiceImpl - Dumb mode not permitted in modal environment; see DumbService.allowStartingDumbModeInside documentation 
java.lang.Throwable
	at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:164)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.doSynchronizeRoots(ProjectRootManagerComponent.java:293)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:414)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:55)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.fireChange(ProjectRootManagerImpl.java:112)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:125)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:352)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$RootProviderChangeListener.rootSetChanged(ProjectRootManagerImpl.java:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy75.rootSetChanged(Unknown Source)
	at com.intellij.openapi.roots.impl.RootProviderBaseImpl.fireRootSetChanged(RootProviderBaseImpl.java:45)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.commit(LibraryImpl.java:614)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.commit(LibraryImpl.java:592)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject.addLibrary$canonical$(IdeaCeylonProject.ceylon:309)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject.addLibrary(IdeaCeylonProject.ceylon:286)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1anonymous_0_.run(IdeaModelLoader.ceylon:67)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:950)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:569)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:396)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:312)
	at com.intellij.openapi.progress.Task.queue(Task.java:96)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$requestRebuild$6(FileBasedIndexImpl.java:1417)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:73)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

The UI isn't frozen, it just shows an empty progress bar:

<img width="1440" alt="capture d ecran 2016-06-16 a 10 29 43" src="https://cloud.githubusercontent.com/assets/281528/16110262/35aaa3b8-33ad-11e6-9cba-a22619d1db61.png">

No thread dump is available.

**Comment by gavinking** [comment]
I have not been experiencing this. Do you guys think it's fixed?

**Comment by bjansen** [comment]
I got it only once, so maybe it's been fixed since then. We can still reopen the issue if it appears again.
