### ISSUE TITLE
impact of quick fix on other file not visible in first file

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#313]
We have some quickfixes, for example "import module", and "create member", that impact a different source file from the one in which they are invoked. In these cases, the impact of the quick fix is not immediately picked up in the editor from which it is invoked, making it look as if the fix didn't work.

(In the Eclipse IDE I actually force navigation to the second file in these cases, so the user can see the impact, but that isn't happening either.)

**Comment by bjansen** [comment]
This is one of the problems in https://github.com/ceylon/ceylon-ide-common/issues/47

**Comment by gavinking** [comment]
Ah, yes, I see. Then close this dupe if you like.

**Comment by bjansen** [comment]
It's actually trickier than I thought, because we need to:

* parse and typecheck the other file affected by the fix (that's easy)
* update the global model (I'm not sure we can do it synchronously)
* parse and typecheck the file on which the quick fix was shown

The third step is needed because as soon as the quick fix has been applied, IntelliJ will try to highlight occurrences of what's under the caret. For example, with the "Make declaration `shared`" quick fix, I we don't typecheck the file, it will still reference the un`shared` declaration, and we'll have errors like this one:

```
[2591133]  ERROR - aemon.impl.PassExecutorService - No PSI node found for ceylon node of type AttributeDeclaration at (183-203).
 
java.lang.IllegalArgumentException: No PSI node found for ceylon node of type AttributeDeclaration at (183-203).

	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonTreeUtil.findPsiElement(CeylonTreeUtil.java:63)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.java:96)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:396)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:373)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:243)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:215)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
```

**Comment by davidfestal** [comment]
I assume this one can be closed also. wdyt @bjansen  ?

**Comment by gavinking** [comment]
Yes, it's fixed, AFAICT.
