### ISSUE TITLE
IllegalStateException: Attempt to modify PSI for non-committed Document!

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#331]
```
Attempt to modify PSI for non-committed Document!
java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document!
	at com.intellij.psi.impl.PsiToDocumentSynchronizer.checkPsiModificationAllowed(PsiToDocumentSynchronizer.java:83)
	at com.intellij.psi.impl.PsiToDocumentSynchronizer.beforeChildrenChange(PsiToDocumentSynchronizer.java:153)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:418)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChildrenChange(PsiManagerImpl.java:270)
	at com.intellij.psi.SingleRootFileViewProvider.onContentReload(SingleRootFileViewProvider.java:224)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$8$1.$call$(CeylonLocalAnalyzerManager.ceylon:183)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$8.$call$(CeylonLocalAnalyzerManager.ceylon:182)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by davidfestal** [comment]
That's easy to fix, I'll do it on Monday.

**Comment by davidfestal** [comment]
@gavinking : I've made an attempt at fixing the cause of this exception. However I could not fully test, since I was not able to reproduce the use-case when the document is uncommitted (which is why this exception was triggered). Can you confirm that it's fixed for you, or provide the use-case that initially triggered this exception for you, so that I can test my fix completely ?

**Comment by davidfestal** [comment]
@gavinking any news?

**Comment by gavinking** [comment]
Well, I don't recall seeing it recently, so let's assume it's fixed for now.
