### ISSUE TITLE
Exception thrown during the change submission task

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-intellij#340]
```
[1016854]   WARN -              ideaPlatformUtils - An exception as thrown during the change submission task 
ceylon.language.Exception "null value returned from native call not assignable to Object"
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$submitChangesTask_.run(CeylonModelManager.ceylon:176)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager.getDelayBeforeUpdatingAfterChange(CeylonModelManager.ceylon:144)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager.scheduleModelUpdate$delay(CeylonModelManager.ceylon:212)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager.scheduleModelUpdate(CeylonModelManager.ceylon:212)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$submitChangesTask_.run(CeylonModelManager.ceylon:169)
	... 6 more

```

**Comment by davidfestal** [comment]
This related to the new delay value that is null. in fact, if I open the settings, the `Languages and Frameworks -> Ceylon -> Editor` is never loaded, and the Code analysis update delay text box is void. it's missing a default value here it seems.

assigning to @bjansen then

**Comment by bjansen** [comment]
What version of IntelliJ are you using?

**Comment by bjansen** [comment]
My bad, I forgot to push a file :(
