### ISSUE TITLE
Bugs in "move statement"

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#357]
In the following code:

```ceylon
    shared actual JMap<JString,DeclarationWithProximity> getAvailableDeclarations
            (String startingWith, Integer proximity, Cancellable? canceller) {
        if (blah) {
        } 
1       value classes = javaFacade(mod.project).findClasses(startingWith, mod.moduleScope);
2       return super.getAvailableDeclarations(startingWith, proximity, canceller);
    }
```

* When I put the caret in whitespaces on line 1 (either before `value` or after the semicolon) and try to move it down, line 2 disappears.
* When I put the caret in line 1 and try to move it up, I expect it to go inside the `if` statement like in Java, but instead it moves above the `if`.

In the following code:

```ceylon
if (blah) {
    value classes = javaFacade(mod.project).findClasses(startingWith, mod.moduleScope);
} 
return super.getAvailableDeclarations(startingWith, proximity, canceller);
```

If I put the caret after the opening curly brace and try to move the `if` statement down, I get this:

```ceylon
    value classes = javaFacade(mod.project).findClasses(startingWith, mod.moduleScope);
if (exists mod = moduleSourceMapper.ceylonProject?.ideArtifact) {
}
return super.getAvailableDeclarations(startingWith, proximity, canceller);
```

instead of 

```ceylon
return super.getAvailableDeclarations(startingWith, proximity, canceller);
if (exists mod = moduleSourceMapper.ceylonProject?.ideArtifact) {
    value classes = javaFacade(mod.project).findClasses(startingWith, mod.moduleScope);
}
```

**Comment by bjansen** [comment]
I just found this stacktrace, although I don't know what text caused it:

```
start > end: start=90; end=89
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.codeInsight.editorActions.moveUpDown.LineRange.<init>(LineRange.java:38)
	at com.intellij.codeInsight.editorActions.moveUpDown.LineRange.<init>(LineRange.java:42)
	at com.intellij.codeInsight.editorActions.moveUpDown.LineRange.<init>(LineRange.java:47)
	at org.intellij.plugins.ceylon.ide.ceylonCode.lang.CeylonStatementUpDownMover.checkAvailable(CeylonStatementUpDownMover.ceylon:66)
	at com.intellij.codeInsight.editorActions.moveUpDown.MoveStatementHandler.getSuitableMover(MoveStatementHandler.java:38)
	at com.intellij.codeInsight.editorActions.moveUpDown.BaseMoveHandler.executeWriteAction(BaseMoveHandler.java:53)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:905)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:70)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$2(CaretModelImpl.java:348)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:437)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:340)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:331)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:88)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:213)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:677)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by gavinking** [comment]
All these issues should now be fixed, except for:

> - When I put the caret in line 1 and try to move it up, I expect it to go inside the `if` statement like in Java, but instead it moves above the `if`.

But TBH, it's not *entirely* clear which behavior is most useful...

**Comment by gavinking** [comment]
This last problem is now fixed. Closing.
