### ISSUE TITLE
`CannotWaitForIndexesInReadAccessError` when trying to resolve a source declaration inside a binary archive during the `TextEditorHighlightingPass`

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-intellij#383]
```
org.intellij.plugins.ceylon.ide.ceylonCode.model.CannotWaitForIndexesInReadAccessError "Waiting for up-to-date indexes inside a read-allowed section is dead-lock-prone."
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needIndexes(concurrencyManager.ceylon:235)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.buildClassMirrorInternal(IdeaModelLoader.ceylon:172)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$11.$call$(IdeModelLoader.ceylon:536)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$11.$call$(IdeModelLoader.ceylon:527)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1anonymous_0_.call(IdeModelLoader.ceylon:133)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:99)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:132)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.lookupNewClassMirror(IdeModelLoader.ceylon:566)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$3.call(AbstractModelLoader.java:433)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$3.call(AbstractModelLoader.java:404)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:99)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.lookupClassMirror(AbstractModelLoader.java:404)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3$1.$call$(IdeModelLoader.ceylon:809)
	at ceylon.language.Iterable$impl.each(Iterable.ceylon:347)
	at ceylon.language.impl.BaseIterable.each(bases.ceylon)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3.$call$(IdeModelLoader.ceylon:804)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3.$call$(IdeModelLoader.ceylon:766)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1anonymous_0_.call(IdeModelLoader.ceylon:133)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:99)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:132)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader.loadPackage(IdeModelLoader.ceylon:823)
	at com.redhat.ceylon.model.loader.model.LazyPackage$2.call(LazyPackage.java:207)
	at com.redhat.ceylon.model.loader.model.LazyPackage$2.call(LazyPackage.java:203)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:79)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getMembers(LazyPackage.java:203)
	at com.redhat.ceylon.ide.common.util.SingleSourceUnitPackage.getMembers(SinceSourceUnitPackage.ceylon:73)
	at com.redhat.ceylon.model.typechecker.model.Package.getDirectMember(Package.java:163)
	at com.redhat.ceylon.ide.common.util.SingleSourceUnitPackage.getDirectMember(SinceSourceUnitPackage.ceylon:61)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.checkForDuplicateDeclaration(DeclarationVisitor.java:525)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visitDeclaration(DeclarationVisitor.java:154)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visitDeclaration(DeclarationVisitor.java:136)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visit(DeclarationVisitor.java:890)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:55)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visit(DeclarationVisitor.java:848)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:945)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:24)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visitAny(DeclarationVisitor.java:692)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visit(DeclarationVisitor.java:724)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.scanDeclarations(PhasedUnit.java:355)
	at com.redhat.ceylon.ide.common.model.IdeModule$24.$call$(IdeModule.ceylon:967)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModule$1.$call$(IdeaModule.ceylon:69)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:186)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModule.encloseOnTheFlyTypechecking(IdeaModule.ceylon:68)
	at com.redhat.ceylon.ide.common.model.IdeModule.buildPhasedUnitForBinaryUnit$priv$(IdeModule.ceylon:963)
	at com.redhat.ceylon.ide.common.model.IdeModule.access$300(IdeModule.ceylon:210)
	at com.redhat.ceylon.ide.common.model.IdeModule$BinaryPhasedUnits.fromStoredType(IdeModule.ceylon:352)
	at com.redhat.ceylon.ide.common.model.IdeModule$BinaryPhasedUnits.fromStoredType(IdeModule.ceylon:307)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnitMap.getPhasedUnit(PhasedUnitMap.java:61)
	at com.redhat.ceylon.ide.common.model.IdeModule$BinaryPhasedUnits.getPhasedUnit(IdeModule.ceylon:329)
	at com.redhat.ceylon.ide.common.model.IdeModule$BinaryPhasedUnits.getPhasedUnit(IdeModule.ceylon:307)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnitMap.getPhasedUnitFromRelativePath(PhasedUnitMap.java:68)
	at com.redhat.ceylon.ide.common.model.IdeModule$BinaryPhasedUnits.getPhasedUnitFromRelativePath(IdeModule.ceylon:345)
	at com.redhat.ceylon.ide.common.model.IdeModule$BinaryPhasedUnits.getPhasedUnitFromRelativePath(IdeModule.ceylon:307)
	at com.redhat.ceylon.ide.common.model.IdeModule$14.$call$(IdeModule.ceylon:648)
	at com.redhat.ceylon.ide.common.model.IdeModule$14.$call$(IdeModule.ceylon:647)
	at com.redhat.ceylon.ide.common.model.IdeModule$10.$call$(IdeModule.ceylon:597)
	at com.redhat.ceylon.ide.common.util.synchronize_.synchronize(synchronize_.java:33)
	at com.redhat.ceylon.ide.common.model.IdeModule.doWithPhasedUnitsObject$priv$(IdeModule.ceylon:595)
	at com.redhat.ceylon.ide.common.model.IdeModule.getPhasedUnitFromRelativePath(IdeModule.ceylon:646)
	at com.redhat.ceylon.ide.common.model.CeylonBinaryUnit.findPhasedUnit(CeylonBinaryUnit.ceylon:35)
	at com.redhat.ceylon.ide.common.model.CeylonBinaryUnit.findPhasedUnit(CeylonBinaryUnit.ceylon:13)
	at com.redhat.ceylon.ide.common.model.CeylonUnit.getPhasedUnit(CeylonUnit.ceylon:39)
	at com.redhat.ceylon.ide.common.model.CeylonBinaryUnit.getPhasedUnit(CeylonBinaryUnit.ceylon:22)
	at com.redhat.ceylon.ide.common.model.CeylonBinaryUnit.getPhasedUnit(CeylonBinaryUnit.ceylon:13)
	at com.redhat.ceylon.ide.common.model.CeylonUnit.getCompilationUnit(CeylonUnit.ceylon:49)
	at com.redhat.ceylon.ide.common.util.nodes_.getReferencedNode$canonical$(nodes.ceylon:482)
	at com.redhat.ceylon.ide.common.util.nodes_.getReferencedNode(nodes.ceylon:473)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.gotoDeclaration(AbstractNavigation.ceylon:167)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation.access$001(ideaNavigation.ceylon:62)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation$1.$call$(ideaNavigation.ceylon:68)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation$1.$call$(ideaNavigation.ceylon:68)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:186)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:198)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.IdeaNavigation.gotoDeclaration(ideaNavigation.ceylon:68)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.resolveDeclaration_.resolveDeclaration(CeylonReference.ceylon:54)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.ceylon:130)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:403)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:380)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:247)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:216)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

```

**Comment by gavinking** [comment]
This is the same as the problem I reported [here](https://github.com/ceylon/ceylon-ide-intellij/issues/355#issuecomment-234734301).

**Comment by davidfestal** [comment]
OK, then it should be fixed locally.I'll push soon.
