### ISSUE TITLE
AssertionError: Already disposed: Project

### ISSUE THREAD

**Issue by azolotko** [ceylon/ceylon-ide-intellij#393]
```
Already disposed: Project (Disposed) arcade
java.lang.AssertionError: Already disposed: Project (Disposed) arcade
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:166)
	at com.intellij.psi.PsiDocumentManager.getInstance(PsiDocumentManager.java:48)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$15$3$1.$call$(CeylonLocalAnalyzerManager.ceylon:241)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$15$3.$call$(CeylonLocalAnalyzerManager.ceylon:240)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

```
IntelliJ IDEA 2016.2.1
Build #IC-162.1447.26, built on August 2, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

ceylon-ide-intellij @ ae026afe0e7d8b2f5dd808885352ddb6e3847e04

Steps to reproduce:

1. Create Ceylon project A (File/New/Project...)
2. Close project A
3. Remove project A from disk
4. Create Ceylon project B

**Comment by gavinking** [comment]
This should now be fixed.
