### ISSUE TITLE
New exception during dependency resolution

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-intellij#401]
this one is new, and is probably related to the last changes @bjansen made on dependencyresolution to avoid intermediate indexing:
```
Do not call synchronous refresh under read lock (except from EDT) - this will cause a deadlock if there are any events to fire.
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.execute(RefreshQueueImpl.java:64)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.launch(RefreshSessionImpl.java:120)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.processSingleEvent(RefreshQueueImpl.java:145)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.createAndFindChildWithEventFire(VirtualDirectoryImpl.java:254)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:96)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.refreshAndFindChild(VirtualDirectoryImpl.java:261)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.refreshAndFindFileByPath(VfsImplUtil.java:136)
	at com.intellij.openapi.vfs.impl.jar.JarFileSystemImpl.refreshAndFindFileByPath(JarFileSystemImpl.java:133)
	at com.intellij.openapi.vfs.impl.VirtualFileManagerImpl.refreshAndFindFileByUrl(VirtualFileManagerImpl.java:147)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.findModuleDescriptorInArtifacts$priv$(IdeaModelLoader.ceylon:211)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.buildClassMirrorInternal(IdeaModelLoader.ceylon:183)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$11.$call$(IdeModelLoader.ceylon:536)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$11.$call$(IdeModelLoader.ceylon:527)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1anonymous_0_.call(IdeModelLoader.ceylon:133)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:115)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:132)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.lookupNewClassMirror(IdeModelLoader.ceylon:566)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$3.call(AbstractModelLoader.java:433)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$3.call(AbstractModelLoader.java:404)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:115)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.lookupClassMirror(AbstractModelLoader.java:404)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadClass(AbstractModelLoader.java:598)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.access$800(AbstractModelLoader.java:100)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$10.call(AbstractModelLoader.java:2132)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$10.call(AbstractModelLoader.java:2119)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1$1.$call$(IdeaModelLoader.ceylon:103)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:192)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.outsideDumbMode(concurrencyManager.ceylon:223)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1.$call$(IdeaModelLoader.ceylon:102)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:125)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:119)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:101)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadCompiledModule(AbstractModelLoader.java:2119)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadCompiledModule(AbstractModelLoader.java:2115)
	at com.redhat.ceylon.compiler.java.loader.model.LazyModuleSourceMapper.resolveModule(LazyModuleSourceMapper.java:128)
	at com.redhat.ceylon.ide.common.model.BaseIdeModuleSourceMapper.resolveModule(IdeModuleSourceMapper.ceylon:148)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.resolveModuleIfRequired(ModuleValidator.java:302)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:226)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.access$500(ModuleValidator.java:39)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:118)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:50)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:75)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:97)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16$1.$call$(CeylonProject.ceylon:918)
	at com.redhat.ceylon.ide.common.model.withCeylonModelCaching_.withCeylonModelCaching(CeylonProjects.ceylon:47)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16.$call$(CeylonProject.ceylon:753)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:440)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:432)
	at com.redhat.ceylon.ide.common.model.CeylonProject.parseCeylonModel(CeylonProject.ceylon:750)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.resolveClasspath$priv$(CeylonProjectBuild.ceylon:572)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild$canonical$(CeylonProjectBuild.ceylon:587)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild(CeylonProjectBuild.ceylon:578)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$2$2$1anonymous_3_$1.$call$(CeylonModelManager.ceylon:386)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:192)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:213)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$2$2$1anonymous_3_.run(CeylonModelManager.ceylon:382)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by davidfestal** [comment]
@bjansen : any idea on this one ? do you think this is fixed ? or might still happen ?

**Comment by bjansen** [comment]
I've never had this exception, so I'm not sure...

**Comment by bjansen** [comment]
I haven't had this exception since that issue was open, so I'm closing it. We can still reopen it if it happens again.

**Comment by bjansen** [comment]
https://gitter.im/ceylon/ceylon-ide-intellij?at=57cd90c4fb58646e42337e39
