### ISSUE TITLE
npe in Extract Value

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#402]
```
null value returned from native call not assignable to Object
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.util.nodes_.renameProposals$canonical$(nodes.ceylon:576)
	at com.redhat.ceylon.ide.common.util.nodes_.renameProposals(nodes.ceylon:567)
	at org.intellij.plugins.ceylon.ide.ceylonCode.refactoring.CeylonNameSuggestionProvider.getSuggestedNames(CeylonNameSuggestionProvider.ceylon:40)
	at com.intellij.refactoring.rename.inplace.MyLookupExpression.initLookupItems(MyLookupExpression.java:68)
	at com.intellij.refactoring.rename.inplace.MyLookupExpression.<init>(MyLookupExpression.java:58)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.createLookupExpression(InplaceRefactoring.java:251)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.addVariable(InplaceRefactoring.java:678)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.addVariable(InplaceRefactoring.java:670)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.buildTemplateAndStart(InplaceRefactoring.java:298)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.buildTemplateAndStart(VariableInplaceRenamer.java:118)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.performInplaceRefactoring(InplaceRefactoring.java:213)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.performInplaceRename(VariableInplaceRenamer.java:94)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.doRename(VariableInplaceRenameHandler.java:121)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.invoke(VariableInplaceRenameHandler.java:90)
	at org.intellij.plugins.ceylon.ide.ceylonCode.refactoring.AbstractExtractHandler.createAndIntroduceValue(AbstractExtractHandler.ceylon:180)
	at org.intellij.plugins.ceylon.ide.ceylonCode.refactoring.AbstractExtractHandler.extractToScope(AbstractExtractHandler.ceylon:83)
	at org.intellij.plugins.ceylon.ide.ceylonCode.refactoring.AbstractExtractHandler.extractSelectedExpression$priv$(AbstractExtractHandler.ceylon:112)
	at org.intellij.plugins.ceylon.ide.ceylonCode.refactoring.AbstractExtractHandler.invoke(AbstractExtractHandler.ceylon:97)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:123)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:677)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by gavinking** [comment]
I have sorta fixed the NPE, but I'm not getting any proposed names, since the root cause is I'm getting passed a `null` instead of a node I use to propose names from. This used to work, IIRC.

**Comment by gavinking** [comment]
Fixed.
