### ISSUE TITLE
StringIndexOutOfBounds

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#425]
```
String index out of range: 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.intellij.configurationStore.ApplicationStorageManager.expandMacros(ApplicationStoreImpl.kt:108)
	at com.intellij.configurationStore.StateStorageManagerImpl.createStateStorage(StateStorageManagerImpl.kt:194)
	at com.intellij.configurationStore.StateStorageManagerImpl.getOrCreateStorage(StateStorageManagerImpl.kt:150)
	at com.intellij.configurationStore.StateStorageManagerImpl.getStateStorage(StateStorageManagerImpl.kt:133)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistentComponent(ComponentStoreImpl.kt:269)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
	at org.intellij.plugins.ceylon.ide.ceylonCode.settings.ceylonSettings_.get_(CeylonSettings.ceylon:18)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager.getDelayBeforeUpdatingAfterChange(CeylonModelManager.ceylon:167)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager.scheduleModelUpdate$delay(CeylonModelManager.ceylon:255)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager.scheduleModelUpdate(CeylonModelManager.ceylon:255)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$submitChangesTask_.run(CeylonModelManager.ceylon:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by bjansen** [comment]
In Android Studio?

**Comment by FroMage** [comment]
Yes
