### ISSUE TITLE
AIOOBE during completion

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#429]
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.scanJavaIndex_$1processor_$1anonymous_1_.<init>(scanJavaIndex.ceylon:221)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.scanJavaIndex_$1processor_.findOrCreateDeclaration$priv$(scanJavaIndex.ceylon:200)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.scanJavaIndex_$1processor_.process(scanJavaIndex.ceylon:359)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.scanJavaIndex_$1processor_.process(scanJavaIndex.ceylon)
	at com.intellij.psi.impl.search.AllClassesSearchExecutor.processClassesByNames(AllClassesSearchExecutor.java:84)
	at com.intellij.codeInsight.completion.AllClassesGetter.processJavaClasses(AllClassesGetter.java:162)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.scanJavaIndex_.scanJavaIndex(scanJavaIndex.ceylon:410)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModule.getAvailableDeclarations(IdeaModule.ceylon:76)
	at com.redhat.ceylon.model.typechecker.model.Package.getMatchingDeclarations(Package.java:241)
	at com.redhat.ceylon.ide.common.util.SingleSourceUnitPackage.getMatchingDeclarations(SinceSourceUnitPackage.ceylon:107)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.TypeDeclaration.getMatchingDeclarations(TypeDeclaration.java:895)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
	at com.redhat.ceylon.ide.common.completion.completionManager_.getProposals$canonical$(IdeCompletionManager.ceylon:1677)
	at com.redhat.ceylon.ide.common.completion.completionManager_.getProposals(IdeCompletionManager.ceylon:1554)
	at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals$canonical$(IdeCompletionManager.ceylon:260)
	at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals(IdeCompletionManager.ceylon:108)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.addCompletionsInternal$priv$(ideaCompletionManager.ceylon:163)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.access$000(ideaCompletionManager.ceylon:59)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider$1.$call$(ideaCompletionManager.ceylon:127)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:192)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:204)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.addCompletions(ideaCompletionManager.ceylon:116)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:776)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:90)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:758)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:856)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gavinking** [comment]
Rebuild the compiler.

**Comment by gavinking** [comment]
For reference @6f4f12457576fccd3e18cd7f9ba132343cb193fc
