### ISSUE TITLE
NoClassDefFoundError in Android Studio

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#437]
```
com/intellij/openapi/diagnostic/ControlFlowException
java.lang.NoClassDefFoundError: com/intellij/openapi/diagnostic/ControlFlowException
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonFile.waitForAnalysisResult$priv$(CeylonFile.ceylon:466)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonFile.waitForAnalysis(CeylonFile.ceylon:238)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonFile.waitForUpToDatePhasedUnit(CeylonFile.ceylon:311)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.NavigationPsiMethod.getParameterList(NavigationPsiMethod.ceylon:127)
	at com.intellij.psi.util.MethodSignatureUtil.areParametersErasureEqual(MethodSignatureUtil.java:292)
	at com.intellij.psi.impl.compiled.ClsMethodImpl.calcSourceMirrorMethod(ClsMethodImpl.java:300)
	at com.intellij.psi.impl.compiled.ClsMethodImpl.access$000(ClsMethodImpl.java:48)
	at com.intellij.psi.impl.compiled.ClsMethodImpl$3.compute(ClsMethodImpl.java:287)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.intellij.psi.impl.compiled.ClsMethodImpl.getSourceMirrorMethod(ClsMethodImpl.java:283)
	at com.intellij.psi.impl.compiled.ClsParameterImpl.isAutoGeneratedName(ClsParameterImpl.java:106)
	at org.jetbrains.kotlin.load.java.structure.impl.JavaValueParameterImpl.getName(JavaValueParameterImpl.java:88)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.resolveValueParameters(LazyJavaScope.kt:195)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.resolveMethodToFunctionDescriptor(LazyJavaScope.kt:122)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$functions$1.invoke(LazyJavaScope.kt:80)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$functions$1.invoke(LazyJavaScope.kt:52)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:394)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:458)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.getContributedFunctions(LazyJavaScope.kt:219)
	at org.jetbrains.kotlin.idea.caches.resolve.JavaResolutionUtils.resolveMethod(JavaResolveExtension.kt:99)
	at org.jetbrains.kotlin.idea.caches.resolve.JavaResolutionUtils.getJavaMethodDescriptor(JavaResolveExtension.kt:44)
	at org.jetbrains.kotlin.idea.caches.resolve.JavaResolutionUtils.getJavaMethodDescriptor$default(JavaResolveExtension.kt:38)
	at org.jetbrains.kotlin.idea.search.ideaExtensions.KotlinPropertyAccessorsReferenceSearcher.propertyName(KotlinPropertyAccessorsReferenceSearcher.kt:55)
	at org.jetbrains.kotlin.idea.search.ideaExtensions.KotlinPropertyAccessorsReferenceSearcher.processQuery(KotlinPropertyAccessorsReferenceSearcher.kt:37)
	at org.jetbrains.kotlin.idea.search.ideaExtensions.KotlinPropertyAccessorsReferenceSearcher.processQuery(KotlinPropertyAccessorsReferenceSearcher.kt:34)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:84)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:78)
	at com.intellij.find.findUsages.JavaFindUsagesHandler.findReferencesToHighlight(JavaFindUsagesHandler.java:241)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getHighlightUsages(IdentifierHighlighterPass.java:139)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightTargetUsages(IdentifierHighlighterPass.java:171)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1180)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.diagnostic.ControlFlowException PluginClassLoader[org.intellij.plugins.ceylon.ide, $pluginVersion$]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 57 more
```

**Comment by davidfestal** [comment]
haha, again an obsolete API in Android Studio.

We could replace that with `ProcessCanceledException`  for the moment I assume.

Ans let the other version commented in the code.
