### ISSUE TITLE
IDE Errors | Not sure if its already reported

### ISSUE THREAD

**Issue by karimiumar** [ceylon/ceylon-ide-intellij#454]
```
2016-09-04 19:12:59,426 [9095850]  ERROR - mpl.search.PsiSearchHelperImpl - No PSI node found for ceylon node of type ObjectDefinition at (471-615).
 
java.lang.IllegalArgumentException: No PSI node found for ceylon node of type ObjectDefinition at (471-615).

	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonTreeUtil.findPsiElement(CeylonTreeUtil.java:61)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.java:86)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.isReferenceTo(CeylonReference.java:138)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:52)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$10.execute(PsiSearchHelperImpl.java:736)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:134)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.access$000(LowLevelSearchUtil.java:47)
	at com.intellij.psi.impl.search.LowLevelSearchUtil$1.execute(LowLevelSearchUtil.java:204)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTextOccurrences(LowLevelSearchUtil.java:271)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:200)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:200)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:188)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:32)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:867)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:29)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:99)
	at com.intellij.concurrency.JobLauncherImpl$$Lambda$190/704062863.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$1(JobLauncherImpl.java:95)
	at com.intellij.concurrency.JobLauncherImpl$$Lambda$189/117935059.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:106)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:52)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processElementsWithWord(PsiSearchHelperImpl.java:208)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processSingleRequest(PsiSearchHelperImpl.java:905)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:597)
	at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:79)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:85)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:57)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:79)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(IdentifierHighlighterPass.java:163)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getHighlightUsages(IdentifierHighlighterPass.java:139)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightTargetUsages(IdentifierHighlighterPass.java:195)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$477/1422489199.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:427)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$473/1471962946.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2016-09-04 19:12:59,428 [9095852]  ERROR - mpl.search.PsiSearchHelperImpl - IntelliJ IDEA 2016.2.3  Build #IC-162.1812.17 
2016-09-04 19:12:59,428 [9095852]  ERROR - mpl.search.PsiSearchHelperImpl - JDK: 1.8.0-tuxjdk 
2016-09-04 19:12:59,428 [9095852]  ERROR - mpl.search.PsiSearchHelperImpl - VM: OpenJDK 64-Bit Client VM 
2016-09-04 19:12:59,429 [9095853]  ERROR - mpl.search.PsiSearchHelperImpl - Vendor: Oracle Corporation 
2016-09-04 19:12:59,429 [9095853]  ERROR - mpl.search.PsiSearchHelperImpl - OS: Linux 
2016-09-04 19:12:59,429 [9095853]  ERROR - mpl.search.PsiSearchHelperImpl - Last Action: EditorPaste 
2016-09-04 19:12:59,911 [9096335]  ERROR - mpl.search.PsiSearchHelperImpl - No PSI node found for ceylon node of type ObjectDefinition at (471-615).
 
java.lang.IllegalArgumentException: No PSI node found for ceylon node of type ObjectDefinition at (471-615).

	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonTreeUtil.findPsiElement(CeylonTreeUtil.java:61)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.java:86)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.isReferenceTo(CeylonReference.java:138)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:52)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$10.execute(PsiSearchHelperImpl.java:736)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:134)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.access$000(LowLevelSearchUtil.java:47)
	at com.intellij.psi.impl.search.LowLevelSearchUtil$1.execute(LowLevelSearchUtil.java:204)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTextOccurrences(LowLevelSearchUtil.java:271)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:200)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:200)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:188)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:32)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:867)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:29)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:99)
	at com.intellij.concurrency.JobLauncherImpl$$Lambda$190/704062863.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$1(JobLauncherImpl.java:95)
	at com.intellij.concurrency.JobLauncherImpl$$Lambda$189/117935059.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:106)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:52)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processElementsWithWord(PsiSearchHelperImpl.java:208)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processSingleRequest(PsiSearchHelperImpl.java:905)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:597)
	at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:79)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:85)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:57)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:79)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(IdentifierHighlighterPass.java:163)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getHighlightUsages(IdentifierHighlighterPass.java:139)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightTargetUsages(IdentifierHighlighterPass.java:195)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:434)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$477/1422489199.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:427)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$$Lambda$473/1471962946.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2016-09-04 19:12:59,913 [9096337]  ERROR - mpl.search.PsiSearchHelperImpl - IntelliJ IDEA 2016.2.3  Build #IC-162.1812.17 
2016-09-04 19:12:59,913 [9096337]  ERROR - mpl.search.PsiSearchHelperImpl - JDK: 1.8.0-tuxjdk 
2016-09-04 19:12:59,913 [9096337]  ERROR - mpl.search.PsiSearchHelperImpl - VM: OpenJDK 64-Bit Client VM 
2016-09-04 19:12:59,913 [9096337]  ERROR - mpl.search.PsiSearchHelperImpl - Vendor: Oracle Corporation 
2016-09-04 19:12:59,913 [9096337]  ERROR - mpl.search.PsiSearchHelperImpl - OS: Linux 
2016-09-04 19:12:59,913 [9096337]  ERROR - mpl.search.PsiSearchHelperImpl - Last Action: EditorCopy 
```

**Comment by bjansen** [comment]
What version of the plugin are you using? That error message has been improved in July to provide much more debugging information.

FTR the readme provides [two installation channels](https://github.com/ceylon/ceylon-ide-intellij#install-from-the-development-plugin-repository). I suggest you use nightly builds, that have huge changes in terms of performance and bug fixes:

https://ci-ceylon.rhcloud.com/job/ceylon-ide-intellij/ws/out/installation-packages/updatePlugins.xml

**Comment by bjansen** [comment]
I confirm that `CeylonTreeUtil.java` doesn't throw exceptions at line 61 since June 16th, so you must be running 1.2.3-201606161613, and that kind of error has very likely been fixed since then. Please retest with nightly builds, and reopen this issue if the problem appears again.
