### ISSUE TITLE
bug that causes model update to be disabled at startup

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#463]
I have seen this a couple of times now, when restarting the IDE:

```
2016-09-07 11:41:41,293 [ 165559]  ERROR - intellij.openapi.progress.Task - Element class com.intellij.psi.impl.source.tree.java.ClassElement of type CLASS 
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.java.ClassElement of type CLASS
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:93)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:96)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:242)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIPackage$1.$call$(PSIPackage.ceylon:21)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIPackage$1.$call$(PSIPackage.ceylon:20)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$2.$call$(concurrencyManager.ceylon:108)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:198)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needReadAccess$canonical$(concurrencyManager.ceylon:115)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needReadAccess(concurrencyManager.ceylon:102)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIPackage.getQualifiedName(PSIPackage.ceylon:20)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getPackageNameForQualifiedClassName(AbstractModelLoader.java:734)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:667)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:662)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.convertToDeclaration(IdeModelLoader.ceylon:521)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3$1.$call$(IdeModelLoader.ceylon:811)
	at ceylon.language.Iterable$impl.each(Iterable.ceylon:352)
	at ceylon.language.impl.BaseIterable.each(bases.ceylon)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3.$call$(IdeModelLoader.ceylon:805)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3.$call$(IdeModelLoader.ceylon:767)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1anonymous_0_.call(IdeModelLoader.ceylon:133)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:122)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:132)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader.loadPackage(IdeModelLoader.ceylon:824)
	at com.redhat.ceylon.model.loader.model.LazyPackage$2.call(LazyPackage.java:207)
	at com.redhat.ceylon.model.loader.model.LazyPackage$2.call(LazyPackage.java:203)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1$1.$call$(IdeaModelLoader.ceylon:105)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.outsideDumbMode(concurrencyManager.ceylon:238)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1.$call$(IdeaModelLoader.ceylon:104)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:125)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:871)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:119)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:101)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getMembers(LazyPackage.java:203)
	at com.redhat.ceylon.ide.common.vfs.FileVirtualFile$impl.getUnit(interfaces.ceylon:252)
	at org.intellij.plugins.ceylon.ide.ceylonCode.vfs.VirtualFileVirtualFile.getUnit(ideaVfs.ceylon)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.getDependentsOf$priv$(CeylonProjectBuild.ceylon:1274)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.access$2100(CeylonProjectBuild.ceylon:122)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$1searchForNewDependencies_$1$1.$iterator$2(CeylonProjectBuild.ceylon:1332)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$1searchForNewDependencies_$1$1.dependingFilePath(CeylonProjectBuild.ceylon:1332)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$1searchForNewDependencies_$1$1.$next$3(CeylonProjectBuild.ceylon:1332)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$1searchForNewDependencies_$1$1.next(CeylonProjectBuild.ceylon:1333)
	at ceylon.language.Array.createArrayFromIterable(Array.java:164)
	at ceylon.language.Array.<init>(Array.java:112)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:278)
	at ceylon.language.impl.BaseIterable.sequence(bases.ceylon)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$1searchForNewDependencies_.searchForNewDependencies(CeylonProjectBuild.ceylon:1335)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.searchForDependantFiles$priv$(CeylonProjectBuild.ceylon:1337)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.calculateDependencies$priv$(CeylonProjectBuild.ceylon:1172)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.consumeModelChanges(CeylonProjectBuild.ceylon:1125)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild$canonical$(CeylonProjectBuild.ceylon:599)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild(CeylonProjectBuild.ceylon:577)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$2$2$1anonymous_4_$1.$call$(CeylonModelManager.ceylon:433)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:228)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$2$2$1anonymous_4_.run(CeylonModelManager.ceylon:428)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-09-07 11:41:41,297 [ 165563]  ERROR - intellij.openapi.progress.Task - IntelliJ IDEA 2016.2.3  Build #IC-162.1812.17 
2016-09-07 11:41:41,297 [ 165563]  ERROR - intellij.openapi.progress.Task - JDK: 1.8.0_112-release 
2016-09-07 11:41:41,297 [ 165563]  ERROR - intellij.openapi.progress.Task - VM: OpenJDK 64-Bit Server VM 
2016-09-07 11:41:41,297 [ 165563]  ERROR - intellij.openapi.progress.Task - Vendor: JetBrains s.r.o 
2016-09-07 11:41:41,297 [ 165563]  ERROR - intellij.openapi.progress.Task - OS: Mac OS X 
2016-09-07 11:41:41,297 [ 165563]  ERROR - intellij.openapi.progress.Task - Last Action: EditorEscape 
 ```

**Comment by bjansen** [comment]
I suppose it's because that class has been reindexed while the model was loading, so we'd probably need to use a `SmartPsiElementPointer`, wdyt @davidfestal ?

**Comment by davidfestal** [comment]
Yes, I think we should use `SmartPsiElementPointer`s in all the class mirrors.

**Comment by bjansen** [comment]
I've added them where necessary. I used to have thousands of similar errors in the problems view right after rebuilding from the CLI, updating the plugin and restarting my main IDE, and now that problem is gone, so I'd say it's fixed.
