### ISSUE TITLE
Errors in 2016.3 EAP

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#470]
I haven't found how to fix this one:

```
[12175764]  ERROR - plication.TransactionGuardImpl - Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities={ModalityState.NON_MODAL=true, ModalityState.NON_MODAL=true, ModalityState.NON_MODAL=true, ModalityState.NON_MODAL=true} 
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
    at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:242)
    at com.intellij.psi.impl.PsiModificationTrackerImpl.fireEvent(PsiModificationTrackerImpl.java:74)
    at com.intellij.psi.impl.PsiModificationTrackerImpl.incCounter(PsiModificationTrackerImpl.java:70)
    at com.intellij.psi.impl.JavaCodeBlockModificationListener.processChange(JavaCodeBlockModificationListener.java:77)
    at com.intellij.psi.impl.JavaCodeBlockModificationListener.treeChanged(JavaCodeBlockModificationListener.java:54)
    at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:362)
    at com.intellij.psi.impl.PsiManagerImpl.childrenChanged(PsiManagerImpl.java:322)
    at com.intellij.psi.SingleRootFileViewProvider.onContentReload(SingleRootFileViewProvider.java:241)
    at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$1commitAndReloadContent_$1.$call$(CeylonLocalAnalyzerManager.ceylon:317)
    at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:913)
    at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$1commitAndReloadContent_.commitAndReloadContent(CeylonLocalAnalyzerManager.ceylon:310)
    at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$24.$call$(CeylonLocalAnalyzerManager.ceylon)
    at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:334)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:836)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:672)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[12175764]  ERROR - plication.TransactionGuardImpl - IntelliJ IDEA (Community Edition) 2016.3 EAP  Build #IC-163.3983.4 
[12175764]  ERROR - plication.TransactionGuardImpl - JDK: 1.8.0_51 
[12175764]  ERROR - plication.TransactionGuardImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
[12175764]  ERROR - plication.TransactionGuardImpl - Vendor: Oracle Corporation 
[12175764]  ERROR - plication.TransactionGuardImpl - OS: Mac OS X 
[12175764]  ERROR - plication.TransactionGuardImpl - Last Action: GotoClass 
```

Using any of `ModalityState.current()`, ModalityState.defaultModalityState()`or`ModalityState.nonModal` does not help :(

**Comment by bjansen** [comment]
Note that it's not a fatal error, merely a big red warning that we are misusing the API.
