### ISSUE TITLE
null member of a TypeDeclaration

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#484]
Well, in theory it's not too hard to add a null check here, but it seems to me that it's a bug in the model loader that the `members` collection contains a null value.

```
null value returned from native call not assignable to Object
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
    at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
    at com.redhat.ceylon.ide.common.completion.completionManager_.isTypeCaseOfSwitch$priv$(IdeCompletionManager.ceylon:1520)
    at com.redhat.ceylon.ide.common.completion.completionManager_.isTypeCaseOfSwitch$priv$(IdeCompletionManager.ceylon:1510)
    at com.redhat.ceylon.ide.common.completion.completionManager_.isCaseOfSwitch$priv$(IdeCompletionManager.ceylon:1430)
    at com.redhat.ceylon.ide.common.completion.completionManager_.isProposable$priv$(IdeCompletionManager.ceylon:1387)
    at com.redhat.ceylon.ide.common.completion.completionManager_.constructCompletions$priv$(IdeCompletionManager.ceylon:932)
    at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals$canonical$(IdeCompletionManager.ceylon:287)
    at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals(IdeCompletionManager.ceylon:113)
    at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.addCompletionsInternal$priv$(ideaCompletionManager.ceylon:211)
    at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.access$000(ideaCompletionManager.ceylon:68)
    at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider$1.$call$(ideaCompletionManager.ceylon:173)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:219)
    at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.addCompletions(ideaCompletionManager.ceylon:140)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
    at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:776)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:90)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:758)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:87)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:84)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:82)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by bjansen** [comment]
I suspect it was fixed in https://github.com/ceylon/ceylon-ide-intellij/commit/e6544592655a60900961b52d44283abdaa4d7a0c, I think `dec.members` was null instead of `m` in the following code:

```ceylon
for (m in dec.members) {
   ...
}
```

Now that we don't return null lists anymore, I believe this issue is fixed.
