### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by vietj** [ceylon/ceylon-ide-intellij#489]
Got this error when loading a project:

```
0
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.intellij.plugins.ceylon.ide.facet.CeylonFacetDetector.setupFacet(CeylonFacetDetector.java:65)
	at org.intellij.plugins.ceylon.ide.facet.CeylonFacetDetector.setupFacet(CeylonFacetDetector.java:36)
	at com.intellij.framework.detection.impl.FacetBasedDetectedFrameworkDescription.doSetup(FacetBasedDetectedFrameworkDescription.java:119)
	at com.intellij.framework.detection.impl.FacetBasedDetectedFrameworkDescriptionImpl.setupFramework(FacetBasedDetectedFrameworkDescriptionImpl.java:53)
	at com.intellij.framework.detection.impl.FrameworkDetectionUtil.setupFrameworks(FrameworkDetectionUtil.java:104)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.a(FrameworkDetectionManager.java:258)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.access$500(FrameworkDetectionManager.java:59)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager$4.hyperlinkUpdate(FrameworkDetectionManager.java:200)
	at com.intellij.notification.impl.ui.NotificationsUtil$1.hyperlinkUpdate(NotificationsUtil.java:149)
	at javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:345)
	at javax.swing.text.html.HTMLEditorKit$LinkController.activateLink(HTMLEditorKit.java:875)
	at javax.swing.text.html.HTMLEditorKit$LinkController.mouseClicked(HTMLEditorKit.java:674)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bjansen** [comment]
Are you opening an existing (configured for Ceylon) project, or importing a Ceylon project from sources?

**Comment by vietj** [comment]
when opening vertx-lang-ceylon project in Intellij

**Comment by bjansen** [comment]
OK, thanks.

**Comment by vietj** [comment]
the current version on GitHub still uses Ceylon 1.2.2 - you should wait that I update it to 1.3.0 before testing

**Comment by bjansen** [comment]
Oh, I think it's because it's a Maven project, so the implicit source directory is `src/main/ceylon`, not `source`.

**Comment by bjansen** [comment]
So, I've fixed the `ArrayIndexOutOfBoundsException`, but I couldn't really make sure that the project opens correctly. Here's what I did:

* cloned the git repo
* IntelliJ detected a `pom.xml`, so it asked if I wanted to open that project, I said yes
* the facet detector detected Ceylon files, so I clicked "configure"
* I had to manually set `src/main/ceylon` as source roots (see #491)
* after reopening the project, the Ceylon model update downloaded a bunch of dependencies, as expected
* there are placeholder versions like `${project.version}` in module descriptors, which prevent the typechecker from being set up correctly

As a result, I still have errors in the Ceylon Problems view, but that's due to the placeholder versions.

**Comment by renatoathaydes** [comment]
I think this has nothing to do with Maven.

Just tried to create a new project from existing sources, pure Ceylon project without Maven or Gradle, and I got the same error. In fact, I am yet to manage to import any project without this error.

The one I tried is [here](https://github.com/renatoathaydes/parcey), if you want to test.

**Comment by bjansen** [comment]
I can import your project just fine using the current master (File > New > Project from existing sources > etc.), so I confirm the problem has been fixed. I will probably make a bugfix release next week.
