### ISSUE TITLE
Error in log  "cannot be cast to java.lang.Short"

### ISSUE THREAD

**Issue by MikhailMalyutin** [ceylon/ceylon-ide-intellij#494]
There is next error in log:
```
com.intellij.psi.impl.compiled.ClsParsingUtil$3 cannot be cast to java.lang.Short
java.lang.ClassCastException: com.intellij.psi.impl.compiled.ClsParsingUtil$3 cannot be cast to java.lang.Short
	at com.redhat.ceylon.compiler.java.loader.AnnotationLoader.loadAnnotationInvocationArguments(AnnotationLoader.java:116)
	at com.redhat.ceylon.compiler.java.loader.AnnotationLoader.loadAnnotationInvocation(AnnotationLoader.java:101)
	at com.redhat.ceylon.compiler.java.loader.AnnotationLoader.setAnnotationConstructor(AnnotationLoader.java:76)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.setAnnotationConstructor(IdeModelLoader.ceylon:400)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$25.run(AbstractModelLoader.java:4746)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:360)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:124)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:357)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:4705)
	at com.redhat.ceylon.model.loader.model.LazyFunction$1.run(LazyFunction.java:87)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:360)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:97)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:357)
	at com.redhat.ceylon.model.loader.model.LazyFunction.load(LazyFunction.java:82)
	at com.redhat.ceylon.model.loader.model.LazyFunction.getParameterLists(LazyFunction.java:129)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.scanJavaIndex_$1processor_$1anonymous_1_.getParameterLists(scanJavaIndex.ceylon:219)
	at com.redhat.ceylon.ide.common.completion.completionManager_.isInvocationProposable$priv$(IdeCompletionManager.ceylon:1359)
	at com.redhat.ceylon.ide.common.completion.completionManager_.constructCompletions$priv$(IdeCompletionManager.ceylon:884)
	at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals$canonical$(IdeCompletionManager.ceylon:287)
	at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals(IdeCompletionManager.ceylon:113)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.addCompletionsInternal$priv$(ideaCompletionManager.ceylon:196)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.access$000(ideaCompletionManager.ceylon:68)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider$1.$call$(ideaCompletionManager.ceylon:158)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:219)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.addCompletions(ideaCompletionManager.ceylon:125)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:843)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$1000(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:825)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:951)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:89)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by bjansen** [comment]
Do you see a warning before that error in the logs, something like "unsupported PsiAnnotationMemberValue xxx"?
