### ISSUE TITLE
Model exception on latest plugin

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#507]
Just got that when upgrading my plugin to the current master.

```
Failed to resolve org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModule
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModule
	at com.redhat.ceylon.model.loader.AbstractModelLoader$5.call(AbstractModelLoader.java:1782)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$5.call(AbstractModelLoader.java:1690)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:336)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1690)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1686)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getDeclaration(AbstractModelLoader.java:5372)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:313)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:305)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:357)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1412)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:265)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:322)
	at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:63)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader.newCompiledUnit(IdeModelLoader.ceylon:717)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.setModuleAndPackageUnits(IdeModelLoader.ceylon:646)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16$1.$call$(CeylonProject.ceylon:927)
	at com.redhat.ceylon.ide.common.model.withCeylonModelCaching_.withCeylonModelCaching(CeylonProjects.ceylon:47)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16.$call$(CeylonProject.ceylon:752)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:440)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:432)
	at com.redhat.ceylon.ide.common.model.CeylonProject.parseCeylonModel(CeylonProject.ceylon:749)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.resolveClasspath$priv$(CeylonProjectBuild.ceylon:572)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild$canonical$(CeylonProjectBuild.ceylon:587)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild(CeylonProjectBuild.ceylon:578)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask$1.$call$(CeylonModelManager.ceylon:317)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:228)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask.run(CeylonModelManager.ceylon:312)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bjansen** [comment]
When opening ceylon-ide-intellij?

**Comment by FroMage** [comment]
Yes, with a Ceylon project open. Or when adding Ceylon to an existing project.

**Comment by FroMage** [comment]
I suppose that blocks me checking your other fixes.

**Comment by FroMage** [comment]
Yeah, it makes the IDE hang when I add the Ceylon nature.

**Comment by bjansen** [comment]
Did you build master or the branch?

**Comment by bjansen** [comment]
If this is the branch, you also have to build the dist, SDK, formatter, converter and ide-common from their `1.3.0` tags (or branch, for ide-common).

**Comment by bjansen** [comment]
Oh, the description says "master", nevermind :)

**Comment by FroMage** [comment]
Yes, `master`.

**Comment by FroMage** [comment]
Are you saying this exception is not present on the new release branch?

**Comment by bjansen** [comment]
I'm not currently experiencing it. But I don't really understand why it happens on master though.

**Comment by bjansen** [comment]
Can't reproduce it here, even on master. Maybe try to rebuild everything again, or do a `File > Invalidate and restart`?

**Comment by FroMage** [comment]
Nope, same. Lemme try the branch.

**Comment by FroMage** [comment]
OK, doesn't happen on the dev site update. I probably fucked up my build.
