### ISSUE TITLE
error at startup in Android Studio

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#522]
I just got this:

```
Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:924)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:872)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:855)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:243)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:224)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClassInIndex(JavaFileManagerImpl.java:122)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:115)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:124)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:101)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:390)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:344)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:336)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:755)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:744)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:371)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:364)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:333)
	at com.intellij.psi.impl.source.PsiImportStatementBaseImpl.resolve(PsiImportStatementBaseImpl.java:64)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarationsNoGuess(PsiJavaFileBaseImpl.java:303)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.access$100(PsiJavaFileBaseImpl.java:58)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl$MyCacheBuilder.compute(PsiJavaFileBaseImpl.java:483)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:272)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:73)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:55)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:223)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:154)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:443)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:344)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:336)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:755)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:744)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:371)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:364)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:145)
	at com.intellij.psi.impl.TypeCorrector.correctType(TypeCorrector.java:56)
	at com.intellij.psi.impl.PsiClassImplUtil.correctType(PsiClassImplUtil.java:732)
	at com.intellij.psi.impl.PsiClassImplUtil.calcScopeCorrectedSuperTypes(PsiClassImplUtil.java:758)
	at com.intellij.psi.impl.PsiClassImplUtil.access$600(PsiClassImplUtil.java:61)
	at com.intellij.psi.impl.PsiClassImplUtil$2$1.create(PsiClassImplUtil.java:745)
	at com.intellij.psi.impl.PsiClassImplUtil$2$1.create(PsiClassImplUtil.java:741)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
	at com.intellij.psi.impl.PsiClassImplUtil.getScopeCorrectedSuperTypes(PsiClassImplUtil.java:751)
	at com.intellij.psi.impl.PsiClassImplUtil.processSuperTypes(PsiClassImplUtil.java:780)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClassNotCached(PsiClassImplUtil.java:722)
	at com.intellij.psi.impl.PsiClassImplUtil.access$500(PsiClassImplUtil.java:61)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:416)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:363)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
	at com.intellij.psi.impl.PsiClassImplUtil.processCachedMembersByName(PsiClassImplUtil.java:556)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:488)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:465)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:491)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:73)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:55)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:223)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:154)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:443)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:344)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:336)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:755)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:271)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:262)
	at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.getQualifiedName(PsiAnnotationImpl.java:96)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIAnnotatedMirror.getAnnotationName$priv$(PSIAnnotatedMirror.ceylon:38)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIAnnotatedMirror.access$100(PSIAnnotatedMirror.ceylon:22)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIAnnotatedMirror$5$1$1$1.$next$2(PSIAnnotatedMirror.ceylon:79)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIAnnotatedMirror$5$1$1$1.next(PSIAnnotatedMirror.ceylon:79)
	at com.redhat.ceylon.compiler.java.language.LazyIterable$LazyIterator.next(LazyIterable.java:73)
	at ceylon.language.Summary.<init>(Iterable.ceylon:1895)
	at ceylon.language.Iterable$impl.summarize(Iterable.ceylon:1754)
	at ceylon.language.impl.BaseIterable.summarize(bases.ceylon)
	at ceylon.language.map_.map(Map.ceylon:452)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIAnnotatedMirror$5.$call$(PSIAnnotatedMirror.ceylon:76)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIAnnotatedMirror$5.$call$(PSIAnnotatedMirror.ceylon:75)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$2.$call$(concurrencyManager.ceylon:108)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:170)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needReadAccess$canonical$(concurrencyManager.ceylon:115)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needReadAccess(concurrencyManager.ceylon:102)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIAnnotatedMirror.getAnnotations$priv$(PSIAnnotatedMirror.ceylon:75)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIAnnotatedMirror.getAnnotation(PSIAnnotatedMirror.ceylon:83)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getClassConstructors(AbstractModelLoader.java:1545)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.createDeclaration(AbstractModelLoader.java:1203)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:696)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:661)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.convertToDeclaration(IdeModelLoader.ceylon:521)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3$1.$call$(IdeModelLoader.ceylon:811)
	at ceylon.language.Iterable$impl.each(Iterable.ceylon:352)
	at ceylon.language.impl.BaseIterable.each(bases.ceylon)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3.$call$(IdeModelLoader.ceylon:805)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3.$call$(IdeModelLoader.ceylon:767)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1anonymous_0_.call(IdeModelLoader.ceylon:133)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:344)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:124)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:340)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:132)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader.loadPackage(IdeModelLoader.ceylon:824)
	at com.redhat.ceylon.model.loader.model.LazyPackage$2.call(LazyPackage.java:220)
	at com.redhat.ceylon.model.loader.model.LazyPackage$2.call(LazyPackage.java:216)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:344)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$2.$call$(IdeaModelLoader.ceylon:116)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:115)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:340)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getMembers(LazyPackage.java:216)
	at com.redhat.ceylon.ide.common.util.SingleSourceUnitPackage.getMembers(SinceSourceUnitPackage.ceylon:65)
	at com.redhat.ceylon.model.typechecker.model.Package.getDirectMember(Package.java:168)
	at com.redhat.ceylon.ide.common.util.SingleSourceUnitPackage.getDirectMember(SinceSourceUnitPackage.ceylon:53)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.checkForDuplicateDeclaration(DeclarationVisitor.java:540)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visitDeclaration(DeclarationVisitor.java:155)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visitDeclaration(DeclarationVisitor.java:137)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visit(DeclarationVisitor.java:905)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:55)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visit(DeclarationVisitor.java:863)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:945)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:24)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visitAny(DeclarationVisitor.java:707)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visit(DeclarationVisitor.java:739)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.scanDeclarations(PhasedUnit.java:355)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer$31$4.$call$(CeylonLocalAnalyzer.ceylon)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer$31.$call$(CeylonLocalAnalyzer.ceylon:566)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer$31.$call$(CeylonLocalAnalyzer.ceylon:524)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:219)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer.createPhasedUnitAndTypecheck$priv$(CeylonLocalAnalyzer.ceylon:524)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer.access$1800(CeylonLocalAnalyzer.ceylon:116)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer$30.$call$(CeylonLocalAnalyzer.ceylon:482)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:446)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:438)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer.typecheckSourceFile$priv$(CeylonLocalAnalyzer.ceylon:411)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer.access$1200(CeylonLocalAnalyzer.ceylon:116)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer$1typecheckingTask_.typecheckingTask(CeylonLocalAnalyzer.ceylon:331)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer$19.$call$(CeylonLocalAnalyzer.ceylon)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzer$9.$call$(CeylonLocalAnalyzer.ceylon:204)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

with this "attachment":

```
java.lang.Throwable
	at com.intellij.openapi.project.DumbServiceImpl.scheduleCacheUpdate(DumbServiceImpl.java:167)
	at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:92)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.doSynchronizeRoots(ProjectRootManagerComponent.java:300)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:419)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:55)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.fireChange(ProjectRootManagerImpl.java:112)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:125)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:324)
	at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.commit(AbstractIdeModifiableModelsProvider.java:367)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject.doWithLibraryModel$priv$(IdeaCeylonProject.ceylon:419)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject.attachSources$priv$(IdeaCeylonProject.ceylon:478)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject.access$300(IdeaCeylonProject.ceylon:135)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject$addModuleArchiveHook_$1anonymous_1_$2.$call$(IdeaCeylonProject.ceylon:228)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:160)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by gavinking** [comment]
Thanks man
