### ISSUE TITLE
Accessing 'java.class.fqn' during processing 'java.class.shortname'. 

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#540]
```
Accessing 'java.class.fqn' during processing 'java.class.shortname'. Nested different indices processing may cause deadlock
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
    at com.intellij.util.indexing.IndexAccessValidator.checkAccessingIndexDuringOtherIndexProcessing(IndexAccessValidator.java:37)
    at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:340)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:316)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:146)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
    at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
    at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:91)
    at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:126)
    at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
    at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:122)
    at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:99)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$5$1.$call$(IdeaModelLoader.ceylon:219)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$5$1.$call$(IdeaModelLoader.ceylon:214)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$2.$call$(concurrencyManager.ceylon:108)
    at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:198)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needReadAccess$canonical$(concurrencyManager.ceylon:115)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needReadAccess(concurrencyManager.ceylon:102)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$5.$call$(IdeaModelLoader.ceylon:214)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$5.$call$(IdeaModelLoader.ceylon:214)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$6.$call$(concurrencyManager.ceylon:244)
    at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
    at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:256)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needIndexes(concurrencyManager.ceylon:251)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.buildClassMirrorInternal(IdeaModelLoader.ceylon:213)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$11.$call$(IdeModelLoader.ceylon:537)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$11.$call$(IdeModelLoader.ceylon:528)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1anonymous_0_.call(IdeModelLoader.ceylon:133)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:347)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:131)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:343)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:132)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.lookupNewClassMirror(IdeModelLoader.ceylon:567)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$3.call(AbstractModelLoader.java:435)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$3.call(AbstractModelLoader.java:406)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:347)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:131)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:343)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.lookupClassMirror(AbstractModelLoader.java:406)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.loadClass(AbstractModelLoader.java:603)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.loadPackageDescriptor(AbstractModelLoader.java:2039)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.access$600(AbstractModelLoader.java:100)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:1997)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:1965)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:347)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:131)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:343)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.findOrCreatePackage(AbstractModelLoader.java:1965)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.access$501(IdeModelLoader.ceylon:100)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$2.$call$(IdeModelLoader.ceylon:178)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$2.$call$(IdeModelLoader.ceylon:177)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1anonymous_0_.call(IdeModelLoader.ceylon:133)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:347)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:131)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:343)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:132)
    at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.findOrCreatePackage(IdeModelLoader.ceylon:193)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$6.call(AbstractModelLoader.java:1945)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$6.call(AbstractModelLoader.java:1925)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:347)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:131)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:343)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.findExistingPackage(AbstractModelLoader.java:1925)
    at com.redhat.ceylon.model.loader.model.LazyModule$1.call(LazyModule.java:129)
    at com.redhat.ceylon.model.loader.model.LazyModule$1.call(LazyModule.java:121)
    at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:347)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:104)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:343)
    at com.redhat.ceylon.model.loader.model.LazyModule.findPackageInModule(LazyModule.java:121)
    at com.redhat.ceylon.model.loader.model.LazyModule.findPackageInImport(LazyModule.java:99)
    at com.redhat.ceylon.model.loader.model.LazyModule.findPackageInImport(LazyModule.java:106)
    at com.redhat.ceylon.model.loader.model.LazyModule.getPackage(LazyModule.java:65)
    at com.redhat.ceylon.ide.common.model.IdeModule.getPackage(IdeModule.ceylon:536)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.scanJavaIndex_$1scope_.contains(scanJavaIndex.ceylon:417)
    at com.intellij.psi.search.DelegatingGlobalSearchScope.contains(DelegatingGlobalSearchScope.java:44)
    at com.intellij.psi.impl.search.JavaSourceFilterScope.contains(JavaSourceFilterScope.java:51)
    at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:321)
    at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:675)
    at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:663)
    at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
    at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:350)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:316)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:146)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
    at com.intellij.psi.impl.java.stubs.index.JavaShortClassNameIndex.get(JavaShortClassNameIndex.java:55)
    at com.intellij.psi.impl.PsiShortNamesCacheImpl.getClassesByName(PsiShortNamesCacheImpl.java:64)
    at com.intellij.psi.impl.CompositeShortNamesCache.getClassesByName(CompositeShortNamesCache.java:77)
    at com.intellij.psi.impl.search.AllClassesSearchExecutor.lambda$processClassesByNames$1(AllClassesSearchExecutor.java:81)
    at com.intellij.psi.impl.search.MethodUsagesSearcher.resolveInReadAction(MethodUsagesSearcher.java:116)
    at com.intellij.psi.impl.search.AllClassesSearchExecutor.processClassesByNames(AllClassesSearchExecutor.java:81)
    at com.intellij.codeInsight.completion.AllClassesGetter.processJavaClasses(AllClassesGetter.java:162)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.scanJavaIndex_.scanJavaIndex(scanJavaIndex.ceylon:428)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModule.getAvailableDeclarations(IdeaModule.ceylon:76)
    at com.redhat.ceylon.model.typechecker.model.Package.getMatchingDeclarations(Package.java:241)
    at com.redhat.ceylon.ide.common.util.SingleSourceUnitPackage.getMatchingDeclarations(SinceSourceUnitPackage.ceylon:107)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.model.typechecker.model.TypeDeclaration.getMatchingDeclarations(TypeDeclaration.java:896)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.model.typechecker.model.NamedArgumentList.getMatchingDeclarations(NamedArgumentList.java:38)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.model.typechecker.model.Element.getMatchingDeclarations(Element.java:246)
    at com.redhat.ceylon.ide.common.completion.completionManager_.getProposals$canonical$(IdeCompletionManager.ceylon:1738)
    at com.redhat.ceylon.ide.common.completion.completionManager_.getProposals(IdeCompletionManager.ceylon:1615)
    at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals$canonical$(IdeCompletionManager.ceylon:266)
    at com.redhat.ceylon.ide.common.completion.completionManager_.getContentProposals(IdeCompletionManager.ceylon:114)
    at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.addCompletionsInternal$priv$(ideaCompletionManager.ceylon:216)
    at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.access$100(ideaCompletionManager.ceylon:70)
    at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider$1.$call$(ideaCompletionManager.ceylon:179)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
    at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:219)
    at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaCompletionProvider.addCompletions(ideaCompletionManager.ceylon:162)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
    at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:776)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:90)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:758)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:87)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:84)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:82)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by gavinking** [comment]
Yay!
