### ISSUE TITLE
error at startup in JS-only project

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#544]
I think this one is a regression:

```
Cannot convert type name "java.lang.CharArray" to a Declaration: Failed to resolve java.lang.CharArray
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve java.lang.CharArray
	at com.redhat.ceylon.model.loader.AbstractModelLoader$5.call(AbstractModelLoader.java:1863)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$5.call(AbstractModelLoader.java:1771)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:348)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:131)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:344)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1771)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1767)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.access$1801(IdeModelLoader.ceylon:100)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$10.$call$(IdeModelLoader.ceylon:508)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$10.$call$(IdeModelLoader.ceylon:497)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1anonymous_0_.call(IdeModelLoader.ceylon:133)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:348)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:131)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:344)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:132)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.convertToDeclaration(IdeModelLoader.ceylon:517)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertDeclaredTypeToDeclaration(AbstractModelLoader.java:650)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertNonPrimitiveTypeToDeclaration(AbstractModelLoader.java:618)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getNonPrimitiveType(AbstractModelLoader.java:5565)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.obtainType(AbstractModelLoader.java:5426)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.obtainType(AbstractModelLoader.java:5381)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.setParameters(AbstractModelLoader.java:4387)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.addMethod(AbstractModelLoader.java:3672)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:3071)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.access$1200(AbstractModelLoader.java:101)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$16.run(AbstractModelLoader.java:2450)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:363)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:348)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:131)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:344)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:360)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2446)
	at com.redhat.ceylon.model.loader.model.LazyClass$1.run(LazyClass.java:97)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:363)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:348)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:131)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:344)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:360)
	at com.redhat.ceylon.model.loader.model.LazyClass.load(LazyClass.java:91)
	at com.redhat.ceylon.model.loader.model.LazyClass.getParameterLists(LazyClass.java:176)
	at com.redhat.ceylon.model.typechecker.model.ModelUtil.hasMatchingSignature(ModelUtil.java:209)
	at com.redhat.ceylon.model.typechecker.model.ModelUtil.hasMatchingSignature(ModelUtil.java:190)
	at com.redhat.ceylon.model.typechecker.model.ModelUtil.lookupMember(ModelUtil.java:2107)
	at com.redhat.ceylon.model.typechecker.model.ModelUtil.lookupMember(ModelUtil.java:2047)
	at com.redhat.ceylon.model.loader.model.LazyPackage$1.call(LazyPackage.java:111)
	at com.redhat.ceylon.model.loader.model.LazyPackage$1.call(LazyPackage.java:98)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:348)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1$1.$call$(IdeaModelLoader.ceylon:114)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.outsideDumbMode(concurrencyManager.ceylon:238)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1.$call$(IdeaModelLoader.ceylon:113)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:125)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:119)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:110)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:344)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getDirectMemberMemoised(LazyPackage.java:98)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getDirectMember(LazyPackage.java:83)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getDirectMember(LazyPackage.java:68)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getMember(LazyPackage.java:62)
	at com.redhat.ceylon.model.typechecker.model.Unit.getImportedDeclaration(Unit.java:176)
	at com.redhat.ceylon.model.typechecker.model.Package.getMemberOrParameter(Package.java:204)
	at com.redhat.ceylon.model.typechecker.model.Element.getMemberOrParameter(Element.java:170)
	at com.redhat.ceylon.model.typechecker.model.Element.getMemberOrParameter(Element.java:150)
	at com.redhat.ceylon.model.typechecker.model.Element.getMemberOrParameter(Element.java:170)
	at com.redhat.ceylon.model.typechecker.model.Element.getMemberOrParameter(Element.java:150)
	at com.redhat.ceylon.compiler.typechecker.analyzer.AnalyzerUtil.getTypeDeclaration(AnalyzerUtil.java:170)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.resolveBaseTypeExpression(ExpressionVisitor.java:7350)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:7292)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$BaseTypeExpression.visit(Tree.java:6431)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:3035)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$InvocationExpression.visit(Tree.java:6202)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkExpression(Walker.java:1387)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Expression.visitChildren(Tree.java:6109)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:24)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:185)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:9553)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:258)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:302)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:256)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:8018)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Expression.visit(Tree.java:6101)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkSpecifierOrInitializerExpression(Walker.java:1662)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkSpecifierExpression(Walker.java:1666)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$SpecifierExpression.visitChildren(Tree.java:7406)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:24)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:298)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:299)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$SpecifierExpression.visit(Tree.java:7398)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkAttributeDeclaration(Walker.java:319)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AttributeDeclaration.visitChildren(Tree.java:1276)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:24)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:131)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:132)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:63)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:2212)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:64)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:65)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:1230)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AttributeDeclaration.visit(Tree.java:1268)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:437)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassBody(Walker.java:446)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visitChildren(Tree.java:1874)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:24)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:83)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:85)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visit(Tree.java:1866)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassDefinition(Walker.java:250)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visitChildren(Tree.java:953)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:24)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:131)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:132)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:42)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:43)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:54)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:55)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:2237)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:945)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:24)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:216)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.analyseTypes(PhasedUnit.java:428)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$21$4.$call$(CeylonProjectBuild.ceylon:753)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$12.$call$(CeylonProjectBuild.ceylon:625)
	at com.redhat.ceylon.compiler.java.Util.apply(Util.java:1640)
	at ceylon.language.unflatten_$1.$call$(unflatten_.java:46)
	at ceylon.language.Iterable$impl.each(Iterable.ceylon:352)
	at ceylon.language.impl.BaseIterable.each(bases.ceylon)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.typecheckDependencies$priv$(CeylonProjectBuild.ceylon:757)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.access$1500(CeylonProjectBuild.ceylon:122)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$27$1$1.$call$(CeylonProjectBuild.ceylon:926)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:452)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:444)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$27$1.$call$(CeylonProjectBuild.ceylon:914)
	at com.redhat.ceylon.ide.common.model.withCeylonModelCaching_.withCeylonModelCaching(CeylonProjects.ceylon:52)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$27.$call$(CeylonProjectBuild.ceylon:913)
	at ceylon.interop.java.internal.synchronize_.synchronize(synchronize_.java:33)
	at ceylon.interop.java.synchronize_.synchronize(misc.ceylon:79)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.updateCeylonModel(CeylonProjectBuild.ceylon:912)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild$canonical$(CeylonProjectBuild.ceylon:610)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild(CeylonProjectBuild.ceylon:580)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask$1.$call$(CeylonModelManager.ceylon:315)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:228)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask.run(CeylonModelManager.ceylon:310)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

And more like that.

**Comment by gavinking** [comment]
This one is a very high priority, since it seems to me that it's the root cause of some really weird compilation errors in JS-only projects.

**Comment by bjansen** [comment]
To fix #456, I changed the initial model update to *not* add `ceylon.language.car` to the classpath, because JS-only projects are supposed to load the language module from sources. What's happening here is that something is still trying to load class mirrors instead of using source declarations, which fails because the language is not in the classpath.

When I tested #456, it was working because there was a 2nd IDEA JVM module that added the .car to the classpath.

**Comment by bjansen** [comment]
After further investigation, I found that the language module is correctly loaded from the .src file, but some of the declarations are written in Java (`java.lang.XxxArray`), so we can't actually load these from source. I need to revert the fix I did in #456, and find something else instead.

Eclipse works fine with ceylon.language.car always in the classpath, so there's no reason I can't do the same in IntelliJ.

**Comment by gavinking** [comment]
@bjansen nononono, you can safely ignore those ones, since they don't actually belong to the language module and aren't available on JS!

**Comment by gavinking** [comment]
Yaaaaaay!

**Comment by bjansen** [comment]
I had the same reaction when I found the root cause :)
