### ISSUE TITLE
Error message in log - Worker exited due to exception

### ISSUE THREAD

**Issue by MikhailMalyutin** [ceylon/ceylon-ide-intellij#545]
```
Worker exited due to exception
java.lang.NullPointerException
	at com.redhat.ceylon.model.loader.model.LazyPackage.isForBackend(LazyPackage.java:189)
	at com.redhat.ceylon.model.loader.model.LazyPackage.access$200(LazyPackage.java:37)
	at com.redhat.ceylon.model.loader.model.LazyPackage$1.call(LazyPackage.java:135)
	at com.redhat.ceylon.model.loader.model.LazyPackage$1.call(LazyPackage.java:98)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:97)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getDirectMemberMemoised(LazyPackage.java:98)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getDirectMemberForBackend(LazyPackage.java:94)
	at com.redhat.ceylon.model.typechecker.model.ModelUtil.getNativeDeclaration(ModelUtil.java:2865)
	at com.redhat.ceylon.model.typechecker.model.ModelUtil.getNativeDeclaration(ModelUtil.java:2790)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.resolveNative(AbstractNavigation.ceylon:158)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.getTarget$canonical$(AbstractNavigation.ceylon:105)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.getTarget(AbstractNavigation.ceylon:57)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference$2.$call$(CeylonReference.ceylon:175)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference$2.$call$(CeylonReference.ceylon:173)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:219)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.ceylon:173)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.resolves(PsiMultiReference.java:62)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.access$000(PsiMultiReference.java:37)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference$1.compare(PsiMultiReference.java:45)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference$1.compare(PsiMultiReference.java:38)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.chooseReference(PsiMultiReference.java:81)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.resolve(PsiMultiReference.java:129)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.resolve(CtrlMouseHandler.java:631)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:533)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:515)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2400(CtrlMouseHandler.java:106)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.doExecute(CtrlMouseHandler.java:844)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$3000(CtrlMouseHandler.java:784)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:829)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:213)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:187)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:211)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gavinking** [comment]
@quintesse would you please give us an idea as to what might be going on here, thanks.

**Comment by bjansen** [comment]
It could be `modelLoader.convertToDeclaration` that is returning null just before calling `if(isForBackend(d, backends))`.
