### ISSUE TITLE
NPE when creating new project

### ISSUE THREAD

**Issue by xkr47** [ceylon/ceylon-ide-intellij#547]
I just downloaded community edition IDEA 2016.2.5, jdk 1.8.0_112-b15 and installed CeylonIDE 1.3.0-201610121525 through IDEA. 

After starting up, creating a new project with all-defaults except the project name & directory (which doesn't exist from before):
```
java.lang.NullPointerException
	at org.intellij.plugins.ceylon.ide.project.PageOne.apply(PageOne.java:93)
	at org.intellij.plugins.ceylon.ide.project.CeylonModuleBuilder.persistConfiguration(CeylonModuleBuilder.java:100)
	at org.intellij.plugins.ceylon.ide.project.CeylonModuleBuilder$1.moduleCreated(CeylonModuleBuilder.java:41)
```
The problem repeats if I choose `File -> Close Project` and create a new project again. The problem **does NOT** repeat if I don't close the current project first.

**Comment by bjansen** [comment]
Already fixed in b8c241fe13e064ca737c12bca38d8d58df73b862
