### ISSUE TITLE
Worker exited due to exception error in log

### ISSUE THREAD

**Issue by MikhailMalyutin** [ceylon/ceylon-ide-intellij#557]
```
Worker exited due to exception
java.lang.NullPointerException
	at com.redhat.ceylon.model.loader.model.LazyPackage.isForBackend(LazyPackage.java:188)
	at com.redhat.ceylon.model.loader.model.LazyPackage.access$200(LazyPackage.java:37)
	at com.redhat.ceylon.model.loader.model.LazyPackage$1.call(LazyPackage.java:135)
	at com.redhat.ceylon.model.loader.model.LazyPackage$1.call(LazyPackage.java:98)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:349)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:105)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:345)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getDirectMemberMemoised(LazyPackage.java:98)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getDirectMemberForBackend(LazyPackage.java:94)
	at com.redhat.ceylon.model.typechecker.model.ModelUtil.getNativeDeclaration(ModelUtil.java:2892)
	at com.redhat.ceylon.model.typechecker.model.ModelUtil.getNativeDeclaration(ModelUtil.java:2818)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.resolveNative(AbstractNavigation.ceylon:161)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.getTarget$canonical$(AbstractNavigation.ceylon:106)
	at com.redhat.ceylon.ide.common.open.AbstractNavigation.getTarget(AbstractNavigation.ceylon:67)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference$2.$call$(CeylonReference.ceylon:176)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference$2.$call$(CeylonReference.ceylon:174)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:219)
	at org.intellij.plugins.ceylon.ide.ceylonCode.resolve.CeylonReference.resolve(CeylonReference.ceylon:174)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.resolves(PsiMultiReference.java:62)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.access$000(PsiMultiReference.java:37)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference$1.compare(PsiMultiReference.java:45)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference$1.compare(PsiMultiReference.java:38)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.cannotChoose(PsiMultiReference.java:138)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.resolve(PsiMultiReference.java:130)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.resolve(CtrlMouseHandler.java:631)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:533)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:515)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2400(CtrlMouseHandler.java:106)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.doExecute(CtrlMouseHandler.java:844)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$3000(CtrlMouseHandler.java:784)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:829)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:213)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:187)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:211)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bjansen** [comment]
You already opened a similar issues 6 days ago, that I fixed this afternoon ;)

https://github.com/ceylon/ceylon-ide-intellij/issues/545
