### ISSUE TITLE
error loading Swarm example project

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#573]
```
Unknown IElementType for + [) [IsCase] (106:14-106:51)
|  +  [TupleType] : [Integer, Calendar]
|  |  +  [BaseType] (106:15-106:21) : Integer : class Integer(Integer integer)
|  |  |  + Integer [Identifier] (106:15-106:21)
|  |  +  [BaseType] (106:33-106:40) : Calendar : class Calendar
|  |  |  + Calendar [Identifier] (106:33-106:40)
|  +  [Variable] : value _ => [Integer, Calendar]
|  |  + _ [Identifier]
|  |  +  [SyntheticVariable] : [Integer, Calendar]
|  |  +  [SpecifierExpression]
|  |  |  +  [Expression] : [Integer|String, Calendar|Date]
|  |  |  |  +  [BaseMemberExpression] : [Integer|String, Calendar|Date] : _ : value _ => [Integer|String, Calendar|Date]
|  |  |  |  |  + _ [Identifier]
|  |  |  |  |  +  [InferredTypeArguments]
 in /Users/gavin/ceylon-sdk/source/ceylon/interop/persistence/BaseQuery.ceylon
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.visitAny(CompilationUnitTranslator.java:133)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.visitAny(CompilationUnitTranslator.java:191)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.visitAny(CompilationUnitTranslator.java:191)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.visitAny(CompilationUnitTranslator.java:191)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.visitAny(CompilationUnitTranslator.java:191)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.visitAny(CompilationUnitTranslator.java:191)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.visitAny(CompilationUnitTranslator.java:191)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.visitAny(CompilationUnitTranslator.java:191)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.visitAny(CompilationUnitTranslator.java:191)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.visit(CompilationUnitTranslator.java:97)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CompilationUnitTranslator.translateToAstNode(CompilationUnitTranslator.java:86)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser.doParseContents(IdeaCeylonParser.ceylon:164)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:246)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:39)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$1triggerReparse_$1.$call$(CeylonLocalAnalyzerManager.ceylon:348)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:843)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$1triggerReparse_.triggerReparse(CeylonLocalAnalyzerManager.ceylon:341)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$23.$call$(CeylonLocalAnalyzerManager.ceylon)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:327)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by gavinking** [comment]
Thanks, that was fast!

**Comment by bjansen** [comment]
Is there any reason why `case ([Integer position, Calendar calendar])` is a `Tree.IsCase` instead of a `CustomTree.IsCase`? That's what caused trouble (the IDE only knew how to map `CustomTree.IsCase`).

**Comment by gavinking** [comment]
Ah, no especially good reason, I suppose, but why are you coding things to depend on `CustomTree` at all? Is there some good reason for that?

**Comment by bjansen** [comment]
When I see an instance of `CustomTree.X`, I still need to convert it to `CeylonPsi.X` when I build the PSI tree.

**Comment by gavinking** [comment]
Right, but why look for `CustomTree.X`?? Why not just look for `Tree.X`?

**Comment by bjansen** [comment]
I'm not using `instanceof`, I'm using a map of `.class -> IElementType`

**Comment by gavinking** [comment]
I see. :-/
