### ISSUE TITLE
Assertion failed: The PSI element should still exist

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#579]
This one is pretty irritating.

```
Assertion failed: The PSI element should still exist
	violated exists el = psiPointer.element
ceylon.language.AssertionError "Assertion failed: The PSI element should still exist
	violated exists el = psiPointer.element"
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIClass.getPsi(PSIClass.ceylon:65)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIClass$3$1$1.<init>(PSIClass.ceylon:108)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIClass$3$1.iterator(PSIClass.ceylon:108)
	at ceylon.language.Array.createArrayFromIterable(Array.java:162)
	at ceylon.language.Array.<init>(Array.java:112)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:278)
	at ceylon.language.impl.BaseIterable.sequence(bases.ceylon)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIClass$3.$call$(PSIClass.ceylon:108)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIClass$3.$call$(PSIClass.ceylon:106)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$1funcRunnable_.funcRunnable(concurrencyManager.ceylon:105)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$2.$call$(concurrencyManager.ceylon)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_$2.run(concurrencyManager.ceylon)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:198)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needReadAccess$canonical$(concurrencyManager.ceylon:112)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.needReadAccess(concurrencyManager.ceylon:99)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.PSIClass.getTypeParameters(PSIClass.ceylon:106)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.setTypeParameters(AbstractModelLoader.java:5401)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.completeTypeParameters(AbstractModelLoader.java:2671)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.access$1300(AbstractModelLoader.java:103)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$17.run(AbstractModelLoader.java:2475)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:368)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:353)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:126)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:349)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:365)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.completeTypeParameters(AbstractModelLoader.java:2471)
	at com.redhat.ceylon.model.loader.model.LazyClass$2.run(LazyClass.java:112)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:368)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:353)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:126)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:349)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:365)
	at com.redhat.ceylon.model.loader.model.LazyClass.loadTypeParams(LazyClass.java:107)
	at com.redhat.ceylon.model.loader.model.LazyClass.access$000(LazyClass.java:30)
	at com.redhat.ceylon.model.loader.model.LazyClass$1.run(LazyClass.java:94)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:368)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:353)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:126)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:349)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:365)
	at com.redhat.ceylon.model.loader.model.LazyClass.load(LazyClass.java:91)
	at com.redhat.ceylon.model.loader.model.LazyClass.getMembers(LazyClass.java:148)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.retrieveInnerDeclarations$priv$(IdeModelLoader.ceylon:236)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.access$600(IdeModelLoader.ceylon:95)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1do_.$do(IdeModelLoader.ceylon:216)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$6.$call$(IdeModelLoader.ceylon)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1.$call$(IdeModelLoader.ceylon)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1.run(IdeModelLoader.ceylon)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:368)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:353)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:126)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:349)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:365)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.runWithLock(IdeModelLoader.ceylon:121)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.removeDeclarations(IdeModelLoader.ceylon:229)
	at com.redhat.ceylon.model.loader.model.LazyPackage$5.run(LazyPackage.java:294)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:368)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:353)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1$1.$call$(IdeaModelLoader.ceylon:111)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:202)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.outsideDumbMode(concurrencyManager.ceylon:233)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1.$call$(IdeaModelLoader.ceylon:110)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1.run(IdeaModelLoader.ceylon:107)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:125)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:119)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:107)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:349)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:365)
	at com.redhat.ceylon.model.loader.model.LazyPackage.removeUnit(LazyPackage.java:279)
	at com.redhat.ceylon.ide.common.model.JavaUnit.remove(JavaUnit.ceylon:29)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.cleanRemovedFilesFromCeylonModel$priv$(CeylonProjectBuild.ceylon:1010)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.consumeModelChanges(CeylonProjectBuild.ceylon:1146)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild$canonical$(CeylonProjectBuild.ceylon:603)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild(CeylonProjectBuild.ceylon:581)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask$1.$call$(CeylonModelManager.ceylon:316)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:202)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:223)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask.run(CeylonModelManager.ceylon:311)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gavinking** [comment]
This could easily be a dupe of #526, thought the stack trace is a bit different.

**Comment by bjansen** [comment]
I'm closing this for now, I hope that catching the exception and forcing a full model update is enough (since some PSI elements are missing, I don't see how else we could make sure that the project is still in a consistent state).

**Comment by NiematojakTomasz** [comment]
Local build from commit https://github.com/ceylon/ceylon-ide-intellij/commit/f72b12ebadc9335088b935921a8c1e0c8022b69b

(There is no CeylonModelManager nor CeylonLocalAnalyzer in the stack trace)

	Assertion failed: The PSI element should still exist
		violated exists el = psiPointer.element
	ceylon.language.AssertionError "Assertion failed: The PSI element should still exist
		violated exists el = psiPointer.element"
		at org.intellij.plugins.ceylon.ide.model.PSIClass.getPsi(PSIClass.ceylon:63)
		at org.intellij.plugins.ceylon.ide.model.PSIClass$6.$call$(PSIClass.ceylon:126)
		at org.intellij.plugins.ceylon.ide.model.PSIClass$6.$call$(PSIClass.ceylon:122)
		at org.intellij.plugins.ceylon.ide.model.concurrencyManager_$1funcRunnable_.funcRunnable(concurrencyManager.ceylon:105)
		at org.intellij.plugins.ceylon.ide.model.concurrencyManager_$2.$call$(concurrencyManager.ceylon)
		at org.intellij.plugins.ceylon.ide.model.concurrencyManager_$2.run(concurrencyManager.ceylon)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:204)
		at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.needReadAccess$canonical$(concurrencyManager.ceylon:112)
		at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.needReadAccess(concurrencyManager.ceylon:99)
		at org.intellij.plugins.ceylon.ide.model.PSIClass.getDirectMethods(PSIClass.ceylon:122)
		at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2810)
		at com.redhat.ceylon.model.loader.AbstractModelLoader.access$1100(AbstractModelLoader.java:103)
		at com.redhat.ceylon.model.loader.AbstractModelLoader$14.run(AbstractModelLoader.java:2491)
		at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:399)
		at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
		at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:135)
		at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
		at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:396)
		at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2487)
		at com.redhat.ceylon.model.loader.model.LazyInterface$1.run(LazyInterface.java:86)
		at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:399)
		at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
		at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader$1$1.$call$(IdeaModelLoader.ceylon:120)
		at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:202)
		at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.outsideDumbMode(concurrencyManager.ceylon:233)
		at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader$1.$call$(IdeaModelLoader.ceylon:119)
		at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader$1.run(IdeaModelLoader.ceylon:116)
		at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:128)
		at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:946)
		at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:124)
		at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:116)
		at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
		at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:396)
		at com.redhat.ceylon.model.loader.model.LazyInterface.load(LazyInterface.java:80)
		at com.redhat.ceylon.model.loader.model.LazyInterface.getCaseTypes(LazyInterface.java:167)
		at com.redhat.ceylon.model.typechecker.model.Type.getCaseTypes(Type.java:2804)
		at com.redhat.ceylon.model.typechecker.model.Type.getUnionOfCasesInternal(Type.java:3351)
		at com.redhat.ceylon.model.typechecker.model.Type.getUnionOfCases(Type.java:3323)
		at com.redhat.ceylon.model.typechecker.model.Type.getUnionOfCasesInternal(Type.java:3370)
		at com.redhat.ceylon.model.typechecker.model.Type.getUnionOfCases(Type.java:3323)
		at com.redhat.ceylon.model.typechecker.model.Type.getUnionOfCasesInternal(Type.java:3370)
		at com.redhat.ceylon.model.typechecker.model.Type.getUnionOfCases(Type.java:3323)
		at com.redhat.ceylon.model.typechecker.model.Type.getUnionOfCasesInternal(Type.java:3370)
		at com.redhat.ceylon.model.typechecker.model.Type.getUnionOfCases(Type.java:3323)
		at com.redhat.ceylon.compiler.typechecker.analyzer.SupertypeVisitor.checkForUndecidability(SupertypeVisitor.java:136)
		at com.redhat.ceylon.compiler.typechecker.analyzer.SupertypeVisitor.visit(SupertypeVisitor.java:238)
		at com.redhat.ceylon.compiler.typechecker.tree.Tree$InterfaceDefinition.visit(Tree.java:1178)
		at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
		at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
		at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:24)
		at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
		at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
		at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.validateRefinement(PhasedUnit.java:409)
		at com.redhat.ceylon.ide.common.model.IdeModule$24.$call$(IdeModule.ceylon:977)
		at org.intellij.plugins.ceylon.ide.model.IdeaModule$12.$call$(IdeaModule.ceylon:129)
		at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:202)
		at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:223)
		at org.intellij.plugins.ceylon.ide.model.IdeaModule.encloseOnTheFlyTypechecking(IdeaModule.ceylon:128)
		at com.redhat.ceylon.ide.common.model.IdeModule.buildPhasedUnitForBinaryUnit$priv$(IdeModule.ceylon:971)
		at com.redhat.ceylon.ide.common.model.IdeModule.access$300(IdeModule.ceylon:215)
		at com.redhat.ceylon.ide.common.model.IdeModule$BinaryPhasedUnits.fromStoredType(IdeModule.ceylon:359)
		at com.redhat.ceylon.ide.common.model.IdeModule$BinaryPhasedUnits.fromStoredType(IdeModule.ceylon:314)
		at com.redhat.ceylon.compiler.typechecker.context.PhasedUnitMap.getPhasedUnits(PhasedUnitMap.java:50)
		at com.redhat.ceylon.ide.common.model.IdeModule$11.$call$(IdeModule.ceylon:614)
		at com.redhat.ceylon.ide.common.model.IdeModule$11.$call$(IdeModule.ceylon:613)
		at com.redhat.ceylon.ide.common.model.IdeModule$10.$call$(IdeModule.ceylon:605)
		at com.redhat.ceylon.ide.common.util.synchronize_.synchronize(synchronize_.java:33)
		at com.redhat.ceylon.ide.common.model.IdeModule.doWithPhasedUnitsObject$priv$(IdeModule.ceylon:603)
		at com.redhat.ceylon.ide.common.model.IdeModule.getPhasedUnits(IdeModule.ceylon:612)
		at org.intellij.plugins.ceylon.ide.hierarchy.collectPhasedUnits_$1.$call$(CeylonHierarchy.ceylon:102)
		at org.intellij.plugins.ceylon.ide.hierarchy.collectPhasedUnits_$1.run(CeylonHierarchy.ceylon:84)
		at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:267)
		at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
		at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
		at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:594)
		at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

**Comment by MikhailMalyutin** [comment]
Nightly build and 2017.1.3:
```
Assertion failed: The PSI element should still exist
	violated exists el = psiPointer.element
ceylon.language.AssertionError "Assertion failed: The PSI element should still exist
	violated exists el = psiPointer.element"
	at org.intellij.plugins.ceylon.ide.model.PSIMethod.getPsi(PSIMethod.ceylon:34)
	at org.intellij.plugins.ceylon.ide.codeInsight.CeylonInlayParameterHintsProvider.getHintInfo(CeylonParameterHintsProvider.ceylon:71)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.process(ParameterHintsPassFactory.java:122)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.lambda$doCollectInformation$2(ParameterHintsPassFactory.java:94)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.doCollectInformation(ParameterHintsPassFactory.java:94)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
