### ISSUE TITLE
RuntimeException during build

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-intellij#582]
```
Failed loading the package list of module ceylon.collection/1.3.0: Failed to read class file for module /home/ceylon/.ceylon/cache/ceylon/collection/1.3.0/ceylon.collection-1.3.0.js
java.lang.RuntimeException: Failed to read class file for module /home/ceylon/.ceylon/cache/ceylon/collection/1.3.0/ceylon.collection-1.3.0.js
	at com.redhat.ceylon.cmr.impl.BytecodeUtils.readModuleInfo(BytecodeUtils.java:167)
	at com.redhat.ceylon.cmr.impl.BytecodeUtils.readModuleInformation(BytecodeUtils.java:101)
	at com.redhat.ceylon.cmr.impl.BytecodeUtils.resolve(BytecodeUtils.java:75)
	at com.redhat.ceylon.cmr.api.AbstractDependencyResolver.resolve(AbstractDependencyResolver.java:30)
	at com.redhat.ceylon.cmr.api.DependencyResolvers.resolve(DependencyResolvers.java:47)
	at com.redhat.ceylon.cmr.impl.AbstractCeylonArtifactResult.resolve(AbstractCeylonArtifactResult.java:59)
	at com.redhat.ceylon.cmr.impl.AbstractCeylonArtifactResult.filter(AbstractCeylonArtifactResult.java:71)
	at com.redhat.ceylon.model.loader.model.LazyModule.loadPackageList(LazyModule.java:174)
	at com.redhat.ceylon.ide.common.model.IdeModule.loadPackageList(IdeModule.ceylon:690)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.addModuleToClassPath(IdeModelLoader.ceylon:557)
	at com.redhat.ceylon.compiler.java.loader.model.LazyModuleSourceMapper.resolveModule(LazyModuleSourceMapper.java:123)
	at com.redhat.ceylon.ide.common.model.BaseIdeModuleSourceMapper.resolveModule(IdeModuleSourceMapper.ceylon:148)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.resolveModuleIfRequired(ModuleValidator.java:312)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:227)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:231)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.access$500(ModuleValidator.java:39)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:119)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:50)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:75)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:97)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16$1.$call$(CeylonProject.ceylon:952)
	at com.redhat.ceylon.ide.common.model.withCeylonModelCaching_.withCeylonModelCaching(CeylonProjects.ceylon:52)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16.$call$(CeylonProject.ceylon:787)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:483)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:475)
	at com.redhat.ceylon.ide.common.model.CeylonProject.parseCeylonModel(CeylonProject.ceylon:784)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.resolveClasspath$priv$(CeylonProjectBuild.ceylon:575)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild$canonical$(CeylonProjectBuild.ceylon:590)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild(CeylonProjectBuild.ceylon:581)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask$1.$call$(CeylonModelManager.ceylon:316)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:202)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:223)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask.run(CeylonModelManager.ceylon:311)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at com.redhat.ceylon.cmr.impl.BytecodeUtils.readModuleInfo(BytecodeUtils.java:149)
	... 45 more


java.lang.RuntimeException: Failed to read class file for module /home/ceylon/.ceylon/cache/ceylon/collection/1.3.0/ceylon.collection-1.3.0.js
	at com.redhat.ceylon.cmr.impl.BytecodeUtils.readModuleInfo(BytecodeUtils.java:167)
	at com.redhat.ceylon.cmr.impl.BytecodeUtils.readModuleInformation(BytecodeUtils.java:101)
	at com.redhat.ceylon.cmr.impl.BytecodeUtils.resolve(BytecodeUtils.java:75)
	at com.redhat.ceylon.cmr.api.AbstractDependencyResolver.resolve(AbstractDependencyResolver.java:30)
	at com.redhat.ceylon.cmr.api.DependencyResolvers.resolve(DependencyResolvers.java:47)
	at com.redhat.ceylon.cmr.impl.AbstractCeylonArtifactResult.resolve(AbstractCeylonArtifactResult.java:59)
	at com.redhat.ceylon.cmr.impl.AbstractCeylonArtifactResult.filter(AbstractCeylonArtifactResult.java:71)
	at com.redhat.ceylon.model.loader.model.LazyModule.loadPackageList(LazyModule.java:174)
	at com.redhat.ceylon.ide.common.model.IdeModule.loadPackageList(IdeModule.ceylon:690)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.addModuleToClassPath(IdeModelLoader.ceylon:557)
	at com.redhat.ceylon.compiler.java.loader.model.LazyModuleSourceMapper.resolveModule(LazyModuleSourceMapper.java:123)
	at com.redhat.ceylon.ide.common.model.BaseIdeModuleSourceMapper.resolveModule(IdeModuleSourceMapper.ceylon:148)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.resolveModuleIfRequired(ModuleValidator.java:312)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:227)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:231)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.access$500(ModuleValidator.java:39)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:119)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:50)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:75)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:97)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16$1.$call$(CeylonProject.ceylon:952)
	at com.redhat.ceylon.ide.common.model.withCeylonModelCaching_.withCeylonModelCaching(CeylonProjects.ceylon:52)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16.$call$(CeylonProject.ceylon:787)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:483)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:475)
	at com.redhat.ceylon.ide.common.model.CeylonProject.parseCeylonModel(CeylonProject.ceylon:784)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.resolveClasspath$priv$(CeylonProjectBuild.ceylon:575)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild$canonical$(CeylonProjectBuild.ceylon:590)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild(CeylonProjectBuild.ceylon:581)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask$1.$call$(CeylonModelManager.ceylon:316)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:202)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:223)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask.run(CeylonModelManager.ceylon:311)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at com.redhat.ceylon.cmr.impl.BytecodeUtils.readModuleInfo(BytecodeUtils.java:149)
	... 45 more


java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
	at com.redhat.ceylon.model.loader.Java9ModuleReader.getClassFile(Java9ModuleReader.java:131)
	at com.redhat.ceylon.model.loader.Java9ModuleReader.getJava9Module(Java9ModuleReader.java:98)
	at com.redhat.ceylon.model.loader.Java9ModuleReader.getExportedPackages(Java9ModuleReader.java:77)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadJava9Module(AbstractModelLoader.java:6375)
	at com.redhat.ceylon.compiler.java.loader.model.LazyModuleSourceMapper.setupJavaModule(LazyModuleSourceMapper.java:184)
	at com.redhat.ceylon.compiler.java.loader.model.LazyModuleSourceMapper.resolveModule(LazyModuleSourceMapper.java:128)
	at com.redhat.ceylon.ide.common.model.BaseIdeModuleSourceMapper.resolveModule(IdeModuleSourceMapper.ceylon:148)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.resolveModuleIfRequired(ModuleValidator.java:312)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:227)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:231)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.access$500(ModuleValidator.java:39)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:119)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:50)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:75)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:97)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16$1.$call$(CeylonProject.ceylon:952)
	at com.redhat.ceylon.ide.common.model.withCeylonModelCaching_.withCeylonModelCaching(CeylonProjects.ceylon:52)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16.$call$(CeylonProject.ceylon:787)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:483)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:475)
	at com.redhat.ceylon.ide.common.model.CeylonProject.parseCeylonModel(CeylonProject.ceylon:784)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.resolveClasspath$priv$(CeylonProjectBuild.ceylon:575)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild$canonical$(CeylonProjectBuild.ceylon:590)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild(CeylonProjectBuild.ceylon:581)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask$1.$call$(CeylonModelManager.ceylon:316)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:202)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:223)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask.run(CeylonModelManager.ceylon:311)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at com.redhat.ceylon.model.loader.Java9ModuleReader.getClassFile(Java9ModuleReader.java:123)
	... 40 more
```

**Comment by quintesse** [comment]
Ok, this is difficult to reproduce. It has to do with the CMR not having been able to download the CAR file, just the JS file.

**Comment by bjansen** [comment]
So if I remove a .car from my `.ceylon/repo`, I should be able to reproduce?

**Comment by quintesse** [comment]
It will just be downloaded again... unless you enable offline perhaps...

**Comment by quintesse** [comment]
Ok, was able to reproduce it now. You have to remove the `xxxx.car*` *and* the `xxxx.src*` files and replace them with `xxxx.car.missing` and `xxxx.src.missing`. Then a simple module that imports `xxxx` is sufficient (in my case `xxxx` is `ceylon.collection-1.3.0` but it should work with anything)

**Comment by bjansen** [comment]
The RuntimeException is gone, but the IDE doesn't show any indication that .src/.car/.jar files are missing (same behavior as the CLI).
