### ISSUE TITLE
Unsupported declaration type: class com.redhat.ceylon.model.typechecker.model.UnknownType error message in log

### ISSUE THREAD

**Issue by MikhailMalyutin** [ceylon/ceylon-ide-intellij#586]
```
Unsupported declaration type: class com.redhat.ceylon.model.typechecker.model.UnknownType
com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError:
Unsupported declaration type: class com.redhat.ceylon.model.typechecker.model.UnknownType
 at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1878)
 at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1873)
 at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForProducedType(Metamodel.java:950)
 at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorsForProducedTypes(Metamodel.java:987)
 at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForProducedType(Metamodel.java:909)
 at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForProducedType(Metamodel.java:912)
 at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getIteratedTypeDescriptor(Metamodel.java:208)
 at ceylon.language.Tuple.computeType(Tuple.java:536)
 at ceylon.language.Tuple.$getType$(Tuple.java:525)
 at ceylon.language.Tuple.$getReifiedElement$(Tuple.java:233)
 at ceylon.language.Tuple$TupleIterator.<init>(Tuple.java:592)
 at ceylon.language.Tuple$TupleIterator.<init>(Tuple.java:588)
 at ceylon.language.Tuple.iterator(Tuple.java:495)
 at org.intellij.plugins.ceylon.ide.ceylonCode.completion.CustomLookupCellRenderer.mergeHighlightAndMatches(CustomLookupCellRenderer.ceylon:281)
 at org.intellij.plugins.ceylon.ide.ceylonCode.completion.CustomLookupCellRenderer.renderItemName$priv$(CustomLookupCellRenderer.ceylon:253)
 at org.intellij.plugins.ceylon.ide.ceylonCode.completion.CustomLookupCellRenderer.customize$priv$(CustomLookupCellRenderer.ceylon:151)
 at org.intellij.plugins.ceylon.ide.ceylonCode.completion.CustomLookupCellRenderer.getListCellRendererComponent(CustomLookupCellRenderer.ceylon:138)
 at com.intellij.codeInsight.lookup.impl.LookupImpl.updateListHeight(LookupImpl.java:419)
 at com.intellij.codeInsight.lookup.impl.LookupImpl.updateList(LookupImpl.java:396)
 at com.intellij.codeInsight.lookup.impl.LookupImpl.refreshUi(LookupImpl.java:1086)
 at com.intellij.codeInsight.completion.CompletionProgressIndicator.hideAutopopupIfMeaningless(CompletionProgressIndicator.java:532)
 at com.intellij.codeInsight.completion.CompletionProgressIndicator.updateLookup(CompletionProgressIndicator.java:335)
 at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$stop$2(CompletionProgressIndicator.java:525)
 at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
 at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
 at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bjansen** [comment]
linked to https://github.com/ceylon/ceylon/issues/6683

**Comment by bjansen** [comment]
This seems to be a problem in Ceylon itself, not in the IDE, so I'm closing this one and reopening  ceylon/ceylon#6683 instead.
