### ISSUE TITLE
completion of module import statement results in error

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#590]
I think this might be new and caused by the latest release of IntelliJ:

```
Wrong endOffset: 69, textLength=65
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$doSetSelection$6(CaretImpl.java:1198)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:444)
	at com.intellij.openapi.editor.impl.CaretImpl.doSetSelection(CaretImpl.java:1185)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1148)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1143)
	at com.intellij.openapi.editor.impl.SelectionModelImpl.setSelection(SelectionModelImpl.java:114)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.setSelection_.setSelection(IdeaCompletionProposal.ceylon:95)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.IdeaModuleCompletionProposal$2.$call$(IdeaModuleCompletionProposal.ceylon:66)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.CompletionHandler.handle$priv$(IdeaCompletionProposal.ceylon:100)
	at org.intellij.plugins.ceylon.ide.ceylonCode.completion.CompletionHandler.handleInsert(IdeaCompletionProposal.ceylon:103)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.handleInsert(LookupElementBuilder.java:389)
	at com.intellij.codeInsight.lookup.LookupElementDecorator.handleInsert(LookupElementDecorator.java:68)
	at com.intellij.codeInsight.lookup.LookupElementDecorator.handleInsert(LookupElementDecorator.java:68)
	at com.intellij.codeInsight.template.impl.TemplateExpressionLookupElement.doHandleInsert(TemplateExpressionLookupElement.java:87)
	at com.intellij.codeInsight.template.impl.TemplateExpressionLookupElement.lambda$handleTemplateInsert$0(TemplateExpressionLookupElement.java:62)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:94)
	at com.intellij.codeInsight.template.impl.TemplateExpressionLookupElement.handleTemplateInsert(TemplateExpressionLookupElement.java:62)
	at com.intellij.codeInsight.template.impl.TemplateState$7.itemSelected(TemplateState.java:685)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.fireItemSelected(LookupImpl.java:826)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:510)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:455)
	at com.intellij.codeInsight.lookup.impl.actions.ChooseItemAction$Handler.execute(ChooseItemAction.java:81)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doExecute(EditorActionHandler.java:172)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:95)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:104)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bjansen** [comment]
I hope it's not a side-effect of this change: https://github.com/ceylon/ceylon-ide-common/commit/f9923e8f26e85422bc66a9f9c93f976261d266b7

Your problem looks like the text changed between the moment the text change was computed and the moment it was applied. Or maybe it was computed on a previous version of the document.

**Comment by bjansen** [comment]
It happened when  the linked mode started for module versions, and I selected a version which was shorter than default version (`1.3.2-SNAPSHOT`). This is now fixed.

**Comment by gavinking** [comment]
Thanks!
