### ISSUE TITLE
error at startup

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#598]
I now always get this error at startup, which stops my initial model update:

```
Failed to resolve org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$24$1anonymous_20_
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$24$1anonymous_20_
	at com.redhat.ceylon.model.loader.AbstractModelLoader$5.call(AbstractModelLoader.java:1908)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$5.call(AbstractModelLoader.java:1816)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:375)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1816)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.addLocalDeclarations(AbstractModelLoader.java:3388)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:3178)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.access$1200(AbstractModelLoader.java:103)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$16.run(AbstractModelLoader.java:2495)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:399)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:375)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:396)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2491)
	at com.redhat.ceylon.model.loader.model.LazyClass$1.run(LazyClass.java:97)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:399)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:375)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:396)
	at com.redhat.ceylon.model.loader.model.LazyClass.load(LazyClass.java:91)
	at com.redhat.ceylon.model.loader.model.LazyClass.getParameterLists(LazyClass.java:176)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForArguments(Metamodel.java:1290)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getAppliedMetamodel(Metamodel.java:652)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getAppliedMetamodel(Metamodel.java:371)
	at ceylon.language.meta.typeLiteral_.typeLiteral(typeLiteral_.java:30)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.analyzerManagerClass_.<clinit>(CeylonFile.ceylon:97)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonFile.getLocalAnalyzer(CeylonFile.ceylon:174)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser.doParseContents(IdeaCeylonParser.ceylon:83)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
	at com.intellij.lang.folding.CustomFoldingBuilder.isCustomFoldingRoot(CustomFoldingBuilder.java:224)
	at com.intellij.lang.folding.CustomFoldingBuilder.addCustomFoldingRegionsRecursively(CustomFoldingBuilder.java:92)
	at com.intellij.lang.folding.CustomFoldingBuilder.buildFoldRegions(CustomFoldingBuilder.java:57)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:236)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:222)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:225)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:54)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader$1.lambda$runBackgroundProcess$1(AsyncEditorLoader.java:83)
	at com.intellij.psi.impl.PsiDocumentManagerBase$6.run(PsiDocumentManagerBase.java:477)
	at com.intellij.psi.impl.PsiDocumentManagerBase$7.compute(PsiDocumentManagerBase.java:506)
	at com.intellij.psi.impl.PsiDocumentManagerBase$7.compute(PsiDocumentManagerBase.java:502)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:899)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:502)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:474)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader$1.runBackgroundProcess(AsyncEditorLoader.java:77)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$null$0(AsyncEditorLoader.java:135)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:135)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$loadImmediately$1(AsyncEditorLoader.java:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bjansen** [comment]
I believe it's the backend that generates invalid code, there's no class named `CeylonLocalAnalyzerManager$24$1anonymous_20_` in the car, but there's a `CeylonLocalAnalyzerManager$20$1anonymous_20_` though.

**Comment by gavinking** [comment]
Is there something with a *similar* name?

**Comment by bjansen** [comment]
OK, we have this generated code:

```java
@LocalDeclarations(value={"24$1anonymous_20_"})
public class CeylonLocalAnalyzerManager {}
```

And these class files:
```
$ jar tf modules/org/intellij/plugins/ceylon/ide/ceylonCode/current/org.intellij.plugins.ceylon.ide.ceylonCode-current.car | grep CeylonLocalAnalyzerManager
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$1.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$10.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$11.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$12.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$13.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$14$1.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$14.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$15.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$16.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$17.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$18.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$19.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$1commitAndReloadContent_$1.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$1commitAndReloadContent_.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$1triggerReparse_$1$1.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$1triggerReparse_$1$2.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$1triggerReparse_$1$3.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$1triggerReparse_$1.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$1triggerReparse_.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$2.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$20$1anonymous_20_.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$20.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$21.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$22.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$23$1.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$23.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$24.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$25.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$3$1.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$3$2$1$1.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$3$2$1.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$3$2.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$3.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$4.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$5.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$6.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$7.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$8.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$9.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$PhasedUnitSynchronizer$1.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager$PhasedUnitSynchronizer.class
org/intellij/plugins/ceylon/ide/ceylonCode/psi/CeylonLocalAnalyzerManager.class
```

So it's clearly the backend that is generating something wrong.

**Comment by gavinking** [comment]
OK, so we need @tombentley or @FroMage to look at this one then.

**Comment by bjansen** [comment]
This is now https://github.com/ceylon/ceylon/issues/6840, I'm leaving this issue open until the one in ceylon/ceylon is fixed.

**Comment by gavinking** [comment]
@bjansen thanks
