### ISSUE TITLE
error finding Implementations

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#604]
```
java.util.ArrayList cannot be cast to ceylon.language.Iterable
java.lang.ClassCastException: java.util.ArrayList cannot be cast to ceylon.language.Iterable
	at com.redhat.ceylon.ide.common.model.IdeModule$11.$call$(IdeModule.ceylon:614)
	at com.redhat.ceylon.ide.common.model.IdeModule$11.$call$(IdeModule.ceylon:613)
	at com.redhat.ceylon.ide.common.model.IdeModule$10.$call$(IdeModule.ceylon:605)
	at com.redhat.ceylon.ide.common.util.synchronize_.synchronize(synchronize_.java:33)
	at com.redhat.ceylon.ide.common.model.IdeModule.doWithPhasedUnitsObject$priv$(IdeModule.ceylon:603)
	at com.redhat.ceylon.ide.common.model.IdeModule.getPhasedUnits(IdeModule.ceylon:612)
	at org.intellij.plugins.ceylon.ide.resolve.CeylonImplementationsSearch.findImplementors$priv$(CeylonImplementationsSearch.ceylon:93)
	at org.intellij.plugins.ceylon.ide.resolve.CeylonImplementationsSearch.execute(CeylonImplementationsSearch.ceylon:53)
	at org.intellij.plugins.ceylon.ide.resolve.CeylonImplementationsSearch.execute(CeylonImplementationsSearch.ceylon:48)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:79)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
```

**Comment by gavinking** [comment]
In fact, looking at the code, this is probably a bug in the compiler. WDYT, @tombentley?

**Comment by gavinking** [comment]
The expression is `{ *phasedUnitMap.phasedUnits }` where `phasedUnitMap.phasedUnits` returns `java.util.List`.

**Comment by gavinking** [comment]
I have opened an issue against the compiler.

**Comment by bjansen** [comment]
Looks like the compiler bug has been fixed, closing.

**Comment by gavinking** [comment]
Great!
