### ISSUE TITLE
java.lang.AssertionError: Already disposed: Project (Disposed)

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#611]
Just go this error after closing a project and opening a different one:

```
Already disposed: Project (Disposed) untitled
java.lang.AssertionError: Already disposed: Project (Disposed) untitled
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:172)
	at com.intellij.openapi.module.ModuleManager.getInstance(ModuleManager.java:42)
	at com.android.tools.idea.databinding.DataBindingProjectComponent$1.compute(DataBindingProjectComponent.java:54)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.android.tools.idea.databinding.DataBindingProjectComponent.getDataBindingEnabledFacets(DataBindingProjectComponent.java:81)
	at com.android.tools.idea.databinding.DataBindingProjectComponent.hasAnyDataBindingEnabledFacet(DataBindingProjectComponent.java:77)
	at com.android.tools.idea.databinding.BrClassFinder.findClass(BrClassFinder.java:58)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:122)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:99)
	at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader$4$1.$call$(IdeaModelLoader.ceylon:212)
	at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader$4$1.$call$(IdeaModelLoader.ceylon:211)
	at org.intellij.plugins.ceylon.ide.model.concurrencyManager_$1funcRunnable_.funcRunnable(concurrencyManager.ceylon:105)
```

**Comment by bjansen** [comment]
How old is your build? It should have been fixed in bf36d766099891f9104a79617bc37a9ae57a2582

**Comment by bjansen** [comment]
I can also reproduce that bug.

**Comment by gavinking** [comment]
Thanks
