### ISSUE TITLE
"Entering in a section that would need indexes" Exception in log

### ISSUE THREAD

**Issue by MikhailMalyutin** [ceylon/ceylon-ide-intellij#621]
```
Entering in a section that would need indexes, but no strategy has been specified.
The strategy used when indexes are unavailable can be specified by one of the following methods:
- concurrencyManager.withUpToDateIndexes()
- concurrencyManager.withAlternateResolution()
- concurrencyManager.outsideDumbMode()
org.intellij.plugins.ceylon.ide.model.IndexNeededWithNoIndexStrategy "Entering in a section that would need indexes, but no strategy has been specified.
The strategy used when indexes are unavailable can be specified by one of the following methods:
- concurrencyManager.withUpToDateIndexes()
- concurrencyManager.withAlternateResolution()
- concurrencyManager.outsideDumbMode()"
	at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.needIndexes(concurrencyManager.ceylon:267)
	at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader.buildClassMirrorInternal(IdeaModelLoader.ceylon:235)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$13.$call$(IdeModelLoader.ceylon:517)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$13.$call$(IdeModelLoader.ceylon:508)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$2.$call$(IdeModelLoader.ceylon:121)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$2.call(IdeModelLoader.ceylon:121)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
	at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:135)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:121)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.lookupNewClassMirror(IdeModelLoader.ceylon:548)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$3.call(AbstractModelLoader.java:480)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$3.call(AbstractModelLoader.java:443)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
	at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:135)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.lookupClassMirror(AbstractModelLoader.java:443)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadClass(AbstractModelLoader.java:648)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadPackageDescriptor(AbstractModelLoader.java:2136)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.access$600(AbstractModelLoader.java:103)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:2090)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:2057)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
	at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:135)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.findOrCreatePackage(AbstractModelLoader.java:2057)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.access$501(IdeModelLoader.ceylon:93)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$4.$call$(IdeModelLoader.ceylon:163)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$4.$call$(IdeModelLoader.ceylon:162)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$2.$call$(IdeModelLoader.ceylon:121)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$2.call(IdeModelLoader.ceylon:121)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:384)
	at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader$2.$call$(IdeaModelLoader.ceylon:128)
	at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader$2.run(IdeaModelLoader.ceylon:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at org.intellij.plugins.ceylon.ide.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:128)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:380)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:121)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.findOrCreatePackage(IdeModelLoader.ceylon:179)
	at com.redhat.ceylon.ide.common.model.CeylonProject$1addIfParentAlreadyAdded_.addIfParentAlreadyAdded(CeylonProject.ceylon:677)
	at com.redhat.ceylon.ide.common.model.CeylonProject.addFolderToModel(CeylonProject.ceylon:689)
	at com.redhat.ceylon.ide.common.model.CeylonProject$1updateModelAndConvertToProjectFileChange_$2convertToVirtualFile_.convertToVirtualFile(CeylonProject.ceylon:1154)
	at com.redhat.ceylon.ide.common.model.CeylonProject$1updateModelAndConvertToProjectFileChange_$2.$call$(CeylonProject.ceylon:1165)
	at com.redhat.ceylon.ide.common.model.CeylonProject$1updateModelAndConvertToProjectFileChange_$2.$call$(CeylonProject.ceylon:1165)
	at com.redhat.ceylon.ide.common.model.ChangeAware$impl.toProjectChange(Changes.ceylon:168)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.toProjectChange(CeylonProjects.ceylon)
	at com.redhat.ceylon.ide.common.model.CeylonProject$1changeAndArtifact_.changeAndArtifact(CeylonProject.ceylon:1179)
	at com.redhat.ceylon.ide.common.model.CeylonProject$18.$call$(CeylonProject.ceylon:1186)
	at ceylon.language.Iterable$impl$3$1.next(Iterable.ceylon:400)
	at com.redhat.ceylon.compiler.java.language.ConstantIterable$1.next(ConstantIterable.java:51)
	at ceylon.language.Category$impl.containsAny(Category.ceylon:95)
	at ceylon.collection.HashSet.containsAny(HashSet.ceylon)
	at com.redhat.ceylon.ide.common.util.ImmutableSetWrapper$6.$call$(ImmutableSetWrapper.ceylon:70)
	at com.redhat.ceylon.ide.common.util.ImmutableSetWrapper$6.$call$(ImmutableSetWrapper.ceylon:69)
	at com.redhat.ceylon.ide.common.util.synchronize_.synchronize(synchronize_.java:33)
	at com.redhat.ceylon.ide.common.util.ImmutableSetWrapper.addAll(ImmutableSetWrapper.ceylon:73)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.fileTreeChanged(CeylonProjectBuild.ceylon:557)
	at com.redhat.ceylon.ide.common.model.CeylonProject.projectFileTreeChanged(CeylonProject.ceylon:1183)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.fileTreeChanged(CeylonProjects.ceylon:203)
	at org.intellij.plugins.ceylon.ide.model.CeylonModelManager.submitChangesTask$priv$(CeylonModelManager.ceylon:258)
	at org.intellij.plugins.ceylon.ide.model.CeylonModelManager.access$000(CeylonModelManager.ceylon:191)
	at org.intellij.plugins.ceylon.ide.model.CeylonModelManager$3.$call$(CeylonModelManager.ceylon:284)
	at org.intellij.plugins.ceylon.ide.model.CeylonModelManager$3.run(CeylonModelManager.ceylon)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MikhailMalyutin** [comment]
Looks like duplicate for https://github.com/ceylon/ceylon-ide-intellij/issues/617

**Comment by gavinking** [comment]
@MikhailMalyutin Did you also get it in AS, or in plain IntelliJ?

**Comment by MikhailMalyutin** [comment]
On plain IntelliJ
