### ISSUE TITLE
Ceylon plugin breaks Java 9 support

### ISSUE THREAD

**Issue by fwgreen** [ceylon/ceylon-ide-intellij#631]
After installing the latest plugin [#256](https://ci-ceylon.rhcloud.com/job/ceylon-ide-intellij/256/), the IDE can't build or execute Java 9 projects.  Things go back to normal once the plugin is removed. 
```
Error:Internal error: (java.lang.ArrayIndexOutOfBoundsException) 1
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.intellij.plugins.ceylon.jps.CeylonBuilderService.createModuleLevelBuilders(CeylonBuilderService.java:19)
	at org.jetbrains.jps.incremental.BuilderRegistry.<init>(BuilderRegistry.java:54)
	at org.jetbrains.jps.incremental.BuilderRegistry.<init>(BuilderRegistry.java:33)
	at org.jetbrains.jps.incremental.BuilderRegistry$Holder.<clinit>(BuilderRegistry.java:36)
	at org.jetbrains.jps.incremental.BuilderRegistry.getInstance(BuilderRegistry.java:43)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:133)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:295)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:236)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1161)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
Idea 2017.1, Windows 10,  JDK 1.8u121 (system default), JDK 9-ea b165

**Comment by bjansen** [comment]
Could you tell me what `System.getProperty("java.version")` returns on your Java 9 install? It looks like the version doesn't start with `1.` anymore... (I suppose it should return the same value as `java -version`).

**Comment by bjansen** [comment]
According to http://openjdk.java.net/jeps/223, versions since Java 9 start with `9`, so I fixed the code to handle that case as well.

**Comment by fwgreen** [comment]
The current version is `9-ea`.  Hopefully your fix does the trick.  Thanks.

**Comment by bjansen** [comment]
I just told Jenkins to rebuild the plugin, you should be able to test the
fix in the next 15min :)
