### ISSUE TITLE
It is possible to obtain StackOverflowError om dependencies

### ISSUE THREAD

**Issue by MikhailMalyutin** [ceylon/ceylon-ide-intellij#633]
```
null
java.lang.StackOverflowError
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$ModuleWeakReference.hashCode(ModuleDependencies.java:125)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:479)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
	at com.redhat.ceylon.ide.common.model.ModuleDependencies$1DependencyAnalyzer.isRootExportedBy(ModuleDependencies.java:498)
```

**Comment by bjansen** [comment]
Do you have a way to reproduce this problem on a simple `module.ceylon` that could could attach to this issue?

**Comment by MikhailMalyutin** [comment]
THis is not easy. This is happened after I try to use com.vasileff.ceylon.structures "1.0.0" module, and additionally I have overrides.xml file

**Comment by MikhailMalyutin** [comment]
And this is floating bug. Then I restart IDEA - all works fine. But later (may be after one hour), then I edit the code, this error is thrown and all code looks invalid. Then I have to restart IDEA again.

**Comment by MikhailMalyutin** [comment]
I have one guess.

In my module I had dependencies:
```
 import maven:org.apache.logging.log4j."log4j-core" "2.8.2";
 import maven:org.apache.logging.log4j."log4j-api" "2.8.2";
```
After I create fat jar and put it to local herd and use import:
```
 import "org.apache.logging.log4j."log4j-core" "2.8.2";
```
Since then I don't see such stacktrace.
