### ISSUE TITLE
errors from FatJarRunConfigurationProducer

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#637]
Got these:

```
null value returned from native call not assignable to Object
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:1007)
	at org.intellij.plugins.ceylon.ide.runner.CeylonTaskRunConfigurationProducer.isConfigurationFromContext(FatJarRunConfigurationProducer.ceylon:56)
	at org.intellij.plugins.ceylon.ide.runner.CeylonTaskRunConfigurationProducer.isConfigurationFromContext(FatJarRunConfigurationProducer.ceylon:34)
	at com.intellij.execution.actions.RunConfigurationProducer.findExistingConfiguration(RunConfigurationProducer.java:210)
	at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:229)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:184)
	at com.intellij.execution.lineMarker.ExecutorAction.update(ExecutorAction.kt:87)
	at com.intellij.execution.lineMarker.LineMarkerActionWrapper.update(LineMarkerActionWrapper.java:84)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.isAvailable(GutterIntentionAction.java:80)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.addActions(GutterIntentionAction.java:147)
```

And:

```
Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals() or TObjectHashingStrategy.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =WeakKey(Ceylon: Ceylon Run Config, 355115237) (class com.intellij.util.containers.WeakHashMap$WeakKey), hashCode=355115237; object #2 =WeakKey(Ceylon: Ceylon Run Config, 355115237) (class com.intellij.util.containers.WeakHashMap$WeakKey), hashCode=355115237
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals() or TObjectHashingStrategy.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =WeakKey(Ceylon: Ceylon Run Config, 355115237) (class com.intellij.util.containers.WeakHashMap$WeakKey), hashCode=355115237; object #2 =WeakKey(Ceylon: Ceylon Run Config, 355115237) (class com.intellij.util.containers.WeakHashMap$WeakKey), hashCode=355115237
	at gnu.trove.TObjectHash.throwObjectContractViolation(TObjectHash.java:319)
	at com.intellij.util.containers.RefHashMap$MyMap.rehash(RefHashMap.java:119)
	at gnu.trove.THash.compact(THash.java:174)
	at com.intellij.util.containers.RefHashMap$MyMap.compact(RefHashMap.java:88)
	at com.intellij.util.containers.RefHashMap$MyMap.compactIfNecessary(RefHashMap.java:95)
	at com.intellij.util.containers.RefHashMap$MyMap.access$400(RefHashMap.java:69)
	at com.intellij.util.containers.RefHashMap.processQueue(RefHashMap.java:181)
	at com.intellij.util.containers.RefHashMap.put(RefHashMap.java:229)
	at com.intellij.util.containers.WeakHashMap.put(WeakHashMap.java:36)
	at com.intellij.execution.impl.RunManagerImpl.setBeforeRunTasks(RunManagerImpl.java:1267)
	at org.intellij.plugins.ceylon.ide.runner.CeylonTaskRunConfigurationProducer.setupConfigurationFromContext(FatJarRunConfigurationProducer.ceylon:87)
	at org.intellij.plugins.ceylon.ide.runner.CeylonTaskRunConfigurationProducer.setupConfigurationFromContext(FatJarRunConfigurationProducer.ceylon:34)
	at com.intellij.execution.actions.RunConfigurationProducer.createLightConfiguration(RunConfigurationProducer.java:255)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.computeConfigurations(ExecutorAction.kt:76)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.getConfigurations(ExecutorAction.kt:62)
	at com.intellij.execution.lineMarker.ExecutorAction$Companion.access$getConfigurations(ExecutorAction.kt:45)
	at com.intellij.execution.lineMarker.ExecutorAction.getActionName(ExecutorAction.kt:108)
	at com.intellij.execution.lineMarker.ExecutorAction.update(ExecutorAction.kt:85)
	at com.intellij.execution.lineMarker.LineMarkerActionWrapper.update(LineMarkerActionWrapper.java:84)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.isAvailable(GutterIntentionAction.java:80)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.addActions(GutterIntentionAction.java:147)
````

**Comment by gavinking** [comment]
The first error should be fixed in 1.3.3. The second I still see from time to time.
