### ISSUE TITLE
problem with blocked internet connection

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#638]
Got this during my demo:

```
java.net.ConnectException: Connection refused
java.lang.RuntimeException: java.net.ConnectException: Connection refused
	at com.redhat.ceylon.cmr.impl.RemoteContentStore.urlExists(RemoteContentStore.java:106)
	at com.redhat.ceylon.cmr.impl.URLContentStore.urlExists(URLContentStore.java:292)
	at com.redhat.ceylon.cmr.impl.URLContentStore.find(URLContentStore.java:234)
	at com.redhat.ceylon.cmr.impl.AbstractOpenNode.getNode(AbstractOpenNode.java:211)
	at com.redhat.ceylon.cmr.impl.AbstractOpenNode.getChild(AbstractOpenNode.java:200)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.fromRepository(AbstractNodeRepositoryManager.java:478)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.fromRepositories(AbstractNodeRepositoryManager.java:454)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.getFromAllRoots(AbstractNodeRepositoryManager.java:436)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.getLeafNode(AbstractNodeRepositoryManager.java:408)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.getArtifactResult(AbstractNodeRepositoryManager.java:171)
	at org.intellij.plugins.ceylon.ide.model.IdeaCeylonProject$addModuleArchiveHook_$1anonymous_0_$1.$call$(IdeaCeylonProject.ceylon:219)
	at org.intellij.plugins.ceylon.ide.model.IdeaCeylonProject$addModuleArchiveHook_$1anonymous_0_$1.$call$(IdeaCeylonProject.ceylon:216)
	at ceylon.language.Iterable$impl$3$1.next(Iterable.ceylon:400)
	at com.redhat.ceylon.compiler.java.language.ConstantIterable$1.next(ConstantIterable.java:51)
	at ceylon.language.Array.createArrayFromIterable(Array.java:164)
	at ceylon.language.Array.<init>(Array.java:112)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:286)
	at ceylon.language.impl.BaseIterable.sequence(bases.ceylon)
	at ceylon.language.Iterable$impl.collect(Iterable.ceylon:926)
	at ceylon.language.impl.BaseIterable.collect(bases.ceylon)
	at org.intellij.plugins.ceylon.ide.model.IdeaCeylonProject$addModuleArchiveHook_$1anonymous_0_.run(IdeaCeylonProject.ceylon:215)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.redhat.ceylon.cmr.impl.URLContentStore.head(URLContentStore.java:391)
	at com.redhat.ceylon.cmr.impl.RemoteContentStore.exists(RemoteContentStore.java:62)
	at com.redhat.ceylon.cmr.impl.RemoteContentStore.urlExists(RemoteContentStore.java:102)
	... 33 more
```

**Comment by vasily-kirichenko** [comment]
I have the same error being behind a proxy:
```
"C:\Program Files\Java\jdk1.8.0_121\bin\java" -Dceylon.system.repo=C:\Users\kirichenko\.IdeaIC2017.2\config\plugins\CeylonIDEA\classes\embeddedDist\repo "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 172.2656.10\lib\idea_rt.jar=28776:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 172.2656.10\bin" -Dfile.encoding=windows-1252 -classpath C:\Users\kirichenko\.IdeaIC2017.2\config\plugins\CeylonIDEA\classes\embeddedDist\lib\ceylon-bootstrap.jar com.redhat.ceylon.launcher.Bootstrap run --run "" default
ceylon run: java.net.ConnectException: Connection refused: connect
java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
	at com.redhat.ceylon.cmr.impl.RemoteContentStore.urlExists(RemoteContentStore.java:106)
	at com.redhat.ceylon.cmr.impl.URLContentStore.urlExists(URLContentStore.java:292)
	at com.redhat.ceylon.cmr.impl.URLContentStore.find(URLContentStore.java:234)
	at com.redhat.ceylon.cmr.impl.AbstractOpenNode.getNode(AbstractOpenNode.java:211)
	at com.redhat.ceylon.cmr.impl.AbstractOpenNode.getChild(AbstractOpenNode.java:200)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.fromRepository(AbstractNodeRepositoryManager.java:478)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.fromRepositories(AbstractNodeRepositoryManager.java:454)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.getFromAllRoots(AbstractNodeRepositoryManager.java:436)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.getLeafNode(AbstractNodeRepositoryManager.java:408)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.getArtifactResult(AbstractNodeRepositoryManager.java:171)
	at com.redhat.ceylon.common.tools.RepoUsingTool.checkModuleVersionsOrShowSuggestions(RepoUsingTool.java:369)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:260)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:547)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:108)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:38)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.redhat.ceylon.launcher.Bootstrap.runVersion(Bootstrap.java:162)
	at com.redhat.ceylon.launcher.Bootstrap.runInternal(Bootstrap.java:117)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:93)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:85)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.redhat.ceylon.cmr.impl.URLContentStore.head(URLContentStore.java:391)
	at com.redhat.ceylon.cmr.impl.RemoteContentStore.exists(RemoteContentStore.java:62)
	at com.redhat.ceylon.cmr.impl.RemoteContentStore.urlExists(RemoteContentStore.java:102)
	... 28 more

Process finished with exit code 2
```
