### ISSUE TITLE
IDE Fatal Error

### ISSUE THREAD

**Issue by andredasilvapinto** [ceylon/ceylon-ide-intellij#64]
I get this error message after creating a new Ceylon project on IntelliJ IDEA Community Edition 14.1.3

```
org.intellij.plugins.ceylon.ide.annotator.TypeCheckerProvider@4558f5df: cannot find module source artifact ceylon.language-1.1.1.src
	- dependency tree: default/unversioned -> ceylon.language/1.1.1
	get ceylon.language and run 'ant publish' (more information at http://ceylon-lang.org/code/source/#ceylonlanguage_module)
com.redhat.ceylon.compiler.typechecker.exceptions.LanguageModuleNotFoundException: cannot find module source artifact ceylon.language-1.1.1.src
	- dependency tree: default/unversioned -> ceylon.language/1.1.1
	get ceylon.language and run 'ant publish' (more information at http://ceylon-lang.org/code/source/#ceylonlanguage_module)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleHelper.buildErrorOnMissingArtifact(ModuleHelper.java:50)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:202)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:86)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.executePhases(TypeChecker.java:149)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:127)
	at com.redhat.ceylon.compiler.typechecker.TypeChecker.process(TypeChecker.java:122)
	at org.intellij.plugins.ceylon.ide.annotator.TypeCheckerProvider.createTypeChecker(TypeCheckerProvider.java:84)
	at org.intellij.plugins.ceylon.ide.annotator.TypeCheckerProvider.projectOpened(TypeCheckerProvider.java:49)
	at com.intellij.openapi.project.impl.ProjectImpl.projectOpened(ProjectImpl.java:385)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:73)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:420)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$3.projectOpened(ProjectManagerImpl.java:154)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:938)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:461)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:562)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:182)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:46)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:357)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:384)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:322)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:309)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:288)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
	at com.sun.proxy.$Proxy58.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:328)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bjansen** [comment]
Did you install both plugins? (CeylonIDEA and CeylonRuntime, as explained in the README)

**Comment by andredasilvapinto** [comment]
Yes

**Comment by bjansen** [comment]
OK, this will likely be fixed when we do a big refactoring to abstract code from the Eclipse plugin and share it with the IntelliJ plugin, which will take some time :(

**Comment by czipperz** [comment]
@bjansen at least part of the problem is that Ceylon 1.1.0 is the current version but its looking for 1.1.1

**Comment by bjansen** [comment]
Yes, the current binaries are based on the dev version of Ceylon, currently 1.1.1 I'll try to have a look at this this week.
Le 21 juin 2015 9:04 PM, Chris Gregory <notifications@github.com> a écrit :@bjansen at least part of the problem is that Ceylon 1.1.0 is the current version but its looking for 1.1.1

**Comment by bjansen** [comment]
@andredasilvapinto and @czipperz I uploaded a new build of the plugin, could you try updating it via `Check for updates`, restart your IDE and tell me if the error is fixed please?
The issue was actually fixed some time ago, but we never released a build that ships this fix :)

**Comment by rlz** [comment]
I have similar problem and upgrading both plugins does not help.

**Comment by bjansen** [comment]
@rlz are you running on Windows? And do you have the exact same error as above?

**Comment by rlz** [comment]
I was running on Linux. Error about missing ceylon.language/1.1.1

**Comment by bjansen** [comment]
But was it just after the project was created, or when you wrote a top level function and tried to compile/ruin it?

**Comment by rlz** [comment]
When I try to compile and run. I got:

> Error:ceylon: com.redhat.ceylon.compiler.typechecker.exceptions.LanguageModuleNotFoundException: cannot find module artifact ceylon.language-1.1.1(.car|.jar)
> 	- dependency tree: default/unversioned -> ceylon.language/1.1.1
> 	get ceylon.language and run 'ant publish' (more information at http://ceylon-lang.org/code/source/#ceylonlanguage_module)

**Comment by bjansen** [comment]
OK, actually this is a separate issue than the original one, but the good news is I fixed them all. I still have a few things to do before I can upload another stable build, but you can expect one in a few days.

Le 6 juil. 2015 1:45 PM, Dmitry Maslennikov <notifications@github.com> a écrit :When I try to compile and run. I got:


Error:ceylon: com.redhat.ceylon.compiler.typechecker.exceptions.LanguageModuleNotFoundException: cannot find module artifact ceylon.language-1.1.1(.car|.jar)

dependency tree: default/unversioned -> ceylon.language/1.1.1
get ceylon.language and run 'ant publish' (more information at http://ceylon-lang.org/code/source/#ceylonlanguage_module)

**Comment by rlz** [comment]
Good news! Waiting for the new build.

**Comment by bjansen** [comment]
I pushed the new build this morning, you should be able to update IntelliJ and build/run things now.

**Comment by rlz** [comment]
Yes. I see similar error messages in Event Log:

> LanguageModuleNotFoundException
>            cannot find module source artifact ceylon.language-1.1.1.src
>            - dependency tree: default/unversioned -> ceylon.language/1.1.1
>            get ceylon.language and run 'ant publish' (more information at http://ceylon-lang.org/code/source/#ceylonlanguage_module)

But able to build and run application.

Thank you for your work! Hope soon it will provide the same functionality as provided by Eclipse based IDE.
