### ISSUE TITLE
CannotRunReadActionException from getDocument() in quick fixes

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#653]
I sometimes get errors like this:

```
com.intellij.openapi.application.ex.ApplicationUtil$CannotRunReadActionException
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.throwIfImpatient(ReadMostlyRWLock.java:126)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.isReadLockedByThisThread(ReadMostlyRWLock.java:89)
	at com.intellij.openapi.application.impl.ApplicationImpl.isReadAccessAllowed(ApplicationImpl.java:1098)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1074)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:184)
	at org.intellij.plugins.ceylon.ide.platform.IdeaTextChange.<init>(IdeaTextChange.ceylon:51)
	at org.intellij.plugins.ceylon.ide.platform.ideaDocumentServices_.createTextChange(ideaDocumentServices.ceylon:14)
	at com.redhat.ceylon.ide.common.correct.createParameterQuickFix_.addCreateParameterProposalInternal$priv$(CreateParameterQuickFix.ceylon:40)
	at com.redhat.ceylon.ide.common.correct.createParameterQuickFix_.addCreateParameterProposal(CreateParameterQuickFix.ceylon:143)
	at com.redhat.ceylon.ide.common.correct.createQuickFix_.addCreateProposals$canonical$(CreateQuickFix.ceylon:275)
	at com.redhat.ceylon.ide.common.correct.createQuickFix_.addCreateProposals(CreateQuickFix.ceylon:261)
	at com.redhat.ceylon.ide.common.correct.ideQuickFixManager_.addCreationProposals$priv$(IdeQuickFixManager.ceylon:267)
	at com.redhat.ceylon.ide.common.correct.ideQuickFixManager_.addQuickFixes(IdeQuickFixManager.ceylon:32)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.addQuickFixes$priv$(CeylonTypeCheckerAnnotator.ceylon:181)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.addAnnotation$priv$(CeylonTypeCheckerAnnotator.ceylon:136)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.access$000(CeylonTypeCheckerAnnotator.ceylon:83)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator$1.$call$(CeylonTypeCheckerAnnotator.ceylon:210)
	at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:199)
	at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:211)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.annotate(CeylonTypeCheckerAnnotator.ceylon:203)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:301)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
com.intellij.openapi.application.ex.ApplicationUtil$CannotRunReadActionException
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.throwIfImpatient(ReadMostlyRWLock.java:126)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.isReadLockedByThisThread(ReadMostlyRWLock.java:89)
	at com.intellij.openapi.application.impl.ApplicationImpl.isReadAccessAllowed(ApplicationImpl.java:1098)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1074)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:184)
	at org.intellij.plugins.ceylon.ide.platform.IdeaTextChange.<init>(IdeaTextChange.ceylon:51)
	at org.intellij.plugins.ceylon.ide.platform.ideaDocumentServices_.createTextChange(ideaDocumentServices.ceylon:14)
	at com.redhat.ceylon.ide.common.correct.removeUnusedDeclarationQuickFix_.addProposal(RemoveUnusedDeclarationQuickFix.ceylon:22)
	at com.redhat.ceylon.ide.common.correct.ideQuickFixManager_.addWarningFixes(IdeQuickFixManager.ceylon:311)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.addQuickFixes$priv$(CeylonTypeCheckerAnnotator.ceylon:179)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.addAnnotation$priv$(CeylonTypeCheckerAnnotator.ceylon:136)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.access$000(CeylonTypeCheckerAnnotator.ceylon:83)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator$1.$call$(CeylonTypeCheckerAnnotator.ceylon:210)
	at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:199)
	at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:211)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.annotate(CeylonTypeCheckerAnnotator.ceylon:203)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:301)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

And this:

```
com.intellij.openapi.application.ex.ApplicationUtil$CannotRunReadActionException
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.throwIfImpatient(ReadMostlyRWLock.java:126)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.isReadLockedByThisThread(ReadMostlyRWLock.java:89)
	at com.intellij.openapi.application.impl.ApplicationImpl.isReadAccessAllowed(ApplicationImpl.java:1098)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1074)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:184)
	at org.intellij.plugins.ceylon.ide.platform.IdeaTextChange.<init>(IdeaTextChange.ceylon:51)
	at org.intellij.plugins.ceylon.ide.platform.ideaDocumentServices_.createTextChange(ideaDocumentServices.ceylon:14)
	at com.redhat.ceylon.ide.common.correct.createParameterQuickFix_.addCreateParameterProposalInternal$priv$(CreateParameterQuickFix.ceylon:40)
	at com.redhat.ceylon.ide.common.correct.createParameterQuickFix_.addCreateParameterProposal(CreateParameterQuickFix.ceylon:143)
	at com.redhat.ceylon.ide.common.correct.createQuickFix_.addCreateProposals$canonical$(CreateQuickFix.ceylon:275)
	at com.redhat.ceylon.ide.common.correct.createQuickFix_.addCreateProposals(CreateQuickFix.ceylon:261)
	at com.redhat.ceylon.ide.common.correct.ideQuickFixManager_.addCreationProposals$priv$(IdeQuickFixManager.ceylon:267)
	at com.redhat.ceylon.ide.common.correct.ideQuickFixManager_.addQuickFixes(IdeQuickFixManager.ceylon:32)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.addQuickFixes$priv$(CeylonTypeCheckerAnnotator.ceylon:181)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.addAnnotation$priv$(CeylonTypeCheckerAnnotator.ceylon:136)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.access$000(CeylonTypeCheckerAnnotator.ceylon:83)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator$1.$call$(CeylonTypeCheckerAnnotator.ceylon:210)
	at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:199)
	at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:211)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.annotate(CeylonTypeCheckerAnnotator.ceylon:203)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:301)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
com.intellij.openapi.application.ex.ApplicationUtil$CannotRunReadActionException
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.throwIfImpatient(ReadMostlyRWLock.java:126)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.isReadLockedByThisThread(ReadMostlyRWLock.java:89)
	at com.intellij.openapi.application.impl.ApplicationImpl.isReadAccessAllowed(ApplicationImpl.java:1098)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1074)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:184)
	at org.intellij.plugins.ceylon.ide.platform.IdeaTextChange.<init>(IdeaTextChange.ceylon:51)
	at org.intellij.plugins.ceylon.ide.platform.ideaDocumentServices_.createTextChange(ideaDocumentServices.ceylon:14)
	at com.redhat.ceylon.ide.common.correct.removeUnusedDeclarationQuickFix_.addProposal(RemoveUnusedDeclarationQuickFix.ceylon:22)
	at com.redhat.ceylon.ide.common.correct.ideQuickFixManager_.addWarningFixes(IdeQuickFixManager.ceylon:311)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.addQuickFixes$priv$(CeylonTypeCheckerAnnotator.ceylon:179)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.addAnnotation$priv$(CeylonTypeCheckerAnnotator.ceylon:136)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.access$000(CeylonTypeCheckerAnnotator.ceylon:83)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator$1.$call$(CeylonTypeCheckerAnnotator.ceylon:210)
	at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:199)
	at org.intellij.plugins.ceylon.ide.model.concurrencyManager_.withAlternateResolution(concurrencyManager.ceylon:211)
	at org.intellij.plugins.ceylon.ide.annotator.CeylonTypeCheckerAnnotator.annotate(CeylonTypeCheckerAnnotator.ceylon:203)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:301)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:327)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

@bjansen would you please take a quick look at this one for me? Thanks!

**Comment by bjansen** [comment]
`ReadMostlyRWLock.throwIfImpatient` LOL
