### ISSUE TITLE
Failed to resolve com.intellij.openapi.module.Module

### ISSUE THREAD

**Issue by paul-dest** [ceylon/ceylon-ide-intellij#659]
Failed to resolve com.intellij.openapi.module.Module
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve com.intellij.openapi.module.Module
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:1995)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:1903)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:409)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:400)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:405)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1903)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1898)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getDeclaration(AbstractModelLoader.java:5893)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:318)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:310)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:361)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:321)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:310)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:361)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:321)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:310)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:361)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1516)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:270)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:326)
	at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:80)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:289)
	at ceylon.language.Map$impl$Items.sequence(Map.ceylon)
	at com.redhat.ceylon.ide.common.model.CeylonProjects$3.$call$(CeylonProjects.ceylon:110)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.withLocking$priv$(CeylonProjects.ceylon:89)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.getCeylonProjects(CeylonProjects.ceylon:108)
	at org.intellij.plugins.ceylon.ide.model.CeylonModelManager$8.$call$(CeylonModelManager.ceylon:413)
	at org.intellij.plugins.ceylon.ide.model.CeylonModelManager$8.run(CeylonModelManager.ceylon:401)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
	at com.intellij.util.Alarm$Request.run(Alarm.java:382)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by davidfestal** [comment]
Could you add the version of the intellij Idea the bug occured on ?

**Comment by paul-dest** [comment]
IntelliJ IDEA 2018.1 (Community Edition)
Build #IC-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by jo5ef** [comment]
I get the same stacktrace when I try to debug a java project. The debugger attaches, but none of the breakpoints are hit and there are no errors in the console. My setup:

IntelliJ IDEA 2018.2.1 (Community Edition)
Build #IC-182.3911.36, built on August 6, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-30-generic

**Comment by mcarifio** [comment]
Has this been resolved? I get a similar error.

**Comment by Swoorup** [comment]
IntelliJ IDEA 2020.3 Beta (Community Edition)
Build #IC-203.5981.41, built on November 19, 2020
Runtime version: 11.0.9+11-b1145.15 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: IdeaVIM, Rider UI Theme Pack, org.toml.lang, intellij.haskell, org.jetbrains.plugins.hocon, org.intellij.scala, org.intellij.plugins.ceylon.ide, org.rust.lang

``` 
Ceylon model update failed
				The Ceylon model update triggered an unexpected exception: com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve com.intellij.openapi.module.Module that will be reported in the Event View.
				To avoid performance issues the automatic update of the Ceylon model has been disabled.
				You can reenable it by using the following menu entry: Tools -> Ceylon -> Enable automatic update of model.
```
