### ISSUE TITLE
Can't rename non-local declarations using dialog

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-intellij#90]
```
Descriptive name not implemented for class org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonPsiImpl$IdentifierPsiImpl
java.lang.UnsupportedOperationException: Descriptive name not implemented for class org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonPsiImpl$IdentifierPsiImpl
	at org.intellij.plugins.ceylon.ide.codeInsight.resolve.CeylonFindUsagesProvider.getDescriptiveName(CeylonFindUsagesProvider.java:103)
	at com.intellij.lang.findUsages.DescriptiveNameUtil.getDescriptiveName(DescriptiveNameUtil.java:48)
	at com.intellij.refactoring.rename.RenameDialog.getFullName(RenameDialog.java:143)
	at com.intellij.refactoring.rename.RenameDialog.getLabelText(RenameDialog.java:115)
	at com.intellij.refactoring.rename.RenameDialog.<init>(RenameDialog.java:88)
```

**Comment by bjansen** [comment]
This has been fixed in 2373473bbbbe33642b6bc380a269c626401c906d.
